//! `schema_version = "1"` — the authoring surface an Execution Identity may be
//! minted from (RFC §6, ADR-015).
//!
//! # Why this is a separate type
//!
//! It is NOT a variant of the v0.3 [`CapsuleManifest`](super::manifest::CapsuleManifest),
//! and there is deliberately no conversion between them. v0.3 cannot express
//! three things v1 identity requires — a guest bind address, an external
//! state's access mode, and a command as an argv rather than a shell string —
//! so any conversion would have to invent them. ADR-015's rule is that a
//! contract is never generated by filling v0.3's ambiguous values with
//! defaults, and the cheapest way to keep that rule is to make the conversion
//! impossible to write by accident.
//!
//! v0.3 keeps working for `run` and `build`, unchanged. It simply never mints.
//!
//! # The authored command is an argv
//!
//! ```toml
//! [run]
//! command = ["python", "-m", "app", "--flag=a b"]
//! ```
//!
//! Four arguments, the last containing a space. There is no string for a
//! quoting mistake to live in, and no implicit shell — RFC §6.1 requires
//! argument boundaries to be preserved exactly, and a shell is available only
//! by asking for one (`["sh", "-lc", "…"]`), which is then visible in the
//! identity as what it is.
//!
//! This is the AUTHORED command. The resolved `launch.argv` recorded in an
//! Execution Contract is what the runner actually starts, which may legitimately
//! wrap it — see ADR-015 §3.
//!
//! # Fail closed, and refuse rather than approximate
//!
//! Unknown fields, duplicate keys and ambiguous defaults are rejected. Features
//! outside the Step-4 vertical subset (ADR-015 §7) are refused BY NAME rather
//! than silently ignored or approximated: a capsule that declares services or
//! dependencies is not a capsule this build can mint an identity for, and
//! saying so is more useful than minting an identity that omits them.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// The only schema version that may mint an Execution Identity.
pub const MANIFEST_SCHEMA_V1: &str = "1";

/// Ceiling for `seal_at.timeout_seconds`, shared with the v0.3 table so one
/// capsule cannot get two answers by changing schema version.
pub use super::ready_state::MAX_SEAL_AT_TIMEOUT_SECONDS;

/// Why a v1 manifest was refused. Every variant is a refusal to proceed, never
/// a value to substitute.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum ManifestV1Error {
    #[error("capsule.toml is not valid TOML: {0}")]
    Toml(String),
    /// The stable code the wire and the CLI both use for "this manifest cannot
    /// mint" (ADR-015 §6.4).
    #[error(
        "execution_identity_requires_manifest_v1: an Execution Identity can only be minted from \
         schema_version = \"1\" (found {found:?}). v0.3 keeps working for run and build; it is \
         not converted, because it cannot express the guest bind address, an external state's \
         access mode, or a command as an argv."
    )]
    RequiresManifestV1 { found: String },
    #[error("{field} is required in a v1 manifest and has no default")]
    Missing { field: &'static str },
    #[error("{field} is invalid: {reason}")]
    Invalid { field: &'static str, reason: String },
    /// A feature outside the Step-4 vertical subset. Named, so the author is
    /// told what to remove rather than left to guess why the identity is wrong.
    #[error(
        "{feature} is not supported by this build's v1 subset (ADR-015 §7): {why}. \
         Use schema_version = \"0.3\" for it — that path is unchanged, it simply does not mint \
         an Execution Identity."
    )]
    Unsupported {
        feature: &'static str,
        why: &'static str,
    },
}

/// The stable error code, for the api and the wizard to key on.
pub const EXECUTION_IDENTITY_REQUIRES_MANIFEST_V1: &str = "execution_identity_requires_manifest_v1";

/// The gate at the entrance of any mint path (ADR-015 §6.4).
///
/// Raised HERE — at the entrance — and never partway through an observation, so
/// the refusal is one behaviour in one place rather than a family of
/// similar-looking failures scattered across the measurement producers.
pub fn require_manifest_v1(schema_version: &str) -> Result<(), ManifestV1Error> {
    if schema_version.trim() == MANIFEST_SCHEMA_V1 {
        return Ok(());
    }
    Err(ManifestV1Error::RequiresManifestV1 {
        found: schema_version.to_string(),
    })
}

/// A v1 `capsule.toml`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CapsuleManifestV1 {
    /// Must be exactly `"1"`. Checked at parse, not at use.
    pub schema_version: String,
    pub name: String,
    pub version: String,

    /// `[tools]` — pinned tool versions, by name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub tools: BTreeMap<String, String>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub build: Option<BuildV1>,

    /// `[run]` — how the workload is started.
    pub run: RunV1,

    /// `[web]` — the guest-facing surface, when the capsule serves one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub web: Option<WebV1>,

    /// `[seal_at]` — the acceptance program. Required to capture interactively;
    /// see [`Self::validate_for_interactive_capture`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seal_at: Option<SealAtV1>,

    /// `[state.<name>]` — external state, fully declared.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub state: BTreeMap<String, StateV1>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BuildV1 {
    /// `[[build.steps]]` — ordered. Each step's `command` is an argv.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub steps: Vec<BuildStepV1>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BuildStepV1 {
    /// Exact argv. No implicit shell.
    pub command: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RunV1 {
    /// Exact argv. No implicit shell (RFC §6.1).
    pub command: Vec<String>,
}

/// `[web]`. Both fields are authored — neither has a default.
///
/// `bind` in particular: `0.0.0.0` appears throughout the tree as a test-fixture
/// value, and ADR-015 §2 forbids promoting a fixture value to a normative
/// default. An author who wants every interface says so.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WebV1 {
    pub port: u16,
    pub bind: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SealAtV1 {
    /// Exact argv, run against a disposable restore. Exit 0 accepts.
    pub command: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<u32>,
}

/// `[state.<name>]`. Every field is authored: this is the declaration an
/// Execution Contract's `external_state` entry is built from, and v0.3 has no
/// counterpart for `access` at all.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StateV1 {
    /// Absolute guest path.
    pub mount: String,
    pub access: StateAccessV1,
    /// Schema identity. The consumer gate is exact string equality with no
    /// migration, so there is no default that could be safely assumed.
    pub schema: String,
    pub snapshot: SnapshotDispositionV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum StateAccessV1 {
    ReadOnly,
    ReadWrite,
}

/// Single-valued in v1, and still stated explicitly rather than implied: an
/// author reading the file should see that state is excluded from the snapshot,
/// not have to know it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SnapshotDispositionV1 {
    Exclude,
}

/// An authored argv, checked the same way everywhere it appears.
///
/// `argv[0]` must be non-empty because it is the program; LATER arguments may
/// be empty, because an empty argument is a real argument and dropping it would
/// change the command. No argument may contain a NUL, which no exec boundary
/// can carry.
fn validate_argv(field: &'static str, argv: &[String]) -> Result<(), ManifestV1Error> {
    if argv.is_empty() {
        return Err(ManifestV1Error::Invalid {
            field,
            reason: "must be a non-empty argv array; a v1 command is never a shell string"
                .to_string(),
        });
    }
    if argv[0].trim().is_empty() {
        return Err(ManifestV1Error::Invalid {
            field,
            reason: "argv[0] is the program and must not be empty".to_string(),
        });
    }
    if let Some(index) = argv.iter().position(|argument| argument.contains('\0')) {
        return Err(ManifestV1Error::Invalid {
            field,
            reason: format!("argv[{index}] must not contain a NUL byte"),
        });
    }
    Ok(())
}

impl CapsuleManifestV1 {
    /// Parse and validate. There is no lenient mode: a manifest that does not
    /// validate is not a v1 manifest.
    pub fn from_toml(text: &str) -> Result<Self, ManifestV1Error> {
        // `deny_unknown_fields` throughout plus toml's own duplicate-key
        // rejection is what makes the accepted spelling single-valued: a typo'd
        // key is an error rather than a silently-ignored intent.
        let manifest: Self =
            toml::from_str(text).map_err(|error| ManifestV1Error::Toml(error.to_string()))?;
        manifest.validate()?;
        Ok(manifest)
    }

    pub fn validate(&self) -> Result<(), ManifestV1Error> {
        require_manifest_v1(&self.schema_version)?;
        for (field, value) in [("name", &self.name), ("version", &self.version)] {
            if value.trim().is_empty() {
                return Err(ManifestV1Error::Missing { field });
            }
        }

        validate_argv("run.command", &self.run.command)?;
        if let Some(build) = &self.build {
            for (index, step) in build.steps.iter().enumerate() {
                validate_argv("build.steps[].command", &step.command).map_err(
                    |error| match error {
                        ManifestV1Error::Invalid { reason, .. } => ManifestV1Error::Invalid {
                            field: "build.steps[].command",
                            reason: format!("step {index}: {reason}"),
                        },
                        other => other,
                    },
                )?;
            }
        }

        if let Some(web) = &self.web {
            if web.port == 0 {
                return Err(ManifestV1Error::Invalid {
                    field: "web.port",
                    reason: "must be 1..=65535".to_string(),
                });
            }
            if web.bind.trim().is_empty() {
                return Err(ManifestV1Error::Missing { field: "web.bind" });
            }
        }

        if let Some(seal_at) = &self.seal_at {
            validate_argv("seal_at.command", &seal_at.command)?;
            match seal_at.timeout_seconds {
                None => {}
                Some(seconds) if (1..=MAX_SEAL_AT_TIMEOUT_SECONDS).contains(&seconds) => {}
                Some(seconds) => {
                    return Err(ManifestV1Error::Invalid {
                        field: "seal_at.timeout_seconds",
                        reason: format!(
                            "must be 1..={MAX_SEAL_AT_TIMEOUT_SECONDS} seconds, got {seconds}"
                        ),
                    });
                }
            }
        }

        for (name, state) in &self.state {
            if name.trim().is_empty() {
                return Err(ManifestV1Error::Missing {
                    field: "state.<name>",
                });
            }
            if !state.mount.starts_with('/')
                || state.mount.contains("/../")
                || state.mount.ends_with("/..")
                || state.mount.ends_with('/')
            {
                return Err(ManifestV1Error::Invalid {
                    field: "state.<name>.mount",
                    reason: format!(
                        "{:?} must be an absolute guest path with no '..' segment and no trailing slash",
                        state.mount
                    ),
                });
            }
            if state.schema.trim().is_empty() {
                return Err(ManifestV1Error::Missing {
                    field: "state.<name>.schema",
                });
            }
        }
        Ok(())
    }

    /// The Step-4 vertical subset (ADR-015 §7).
    ///
    /// Separate from [`Self::validate`] because these are not malformed
    /// manifests — they are perfectly good capsules this build cannot yet mint
    /// an identity for. A `run`/`build` caller must not be blocked by them.
    pub fn validate_for_interactive_capture(&self) -> Result<(), ManifestV1Error> {
        self.validate()?;

        if !self.tools.is_empty() {
            return Err(ManifestV1Error::Unsupported {
                feature: "[tools]",
                why: "a pinned tool is a dependency, and per-dependency derivation and output \
                      digests have no producer yet, so its identity could not be measured",
            });
        }
        if self
            .build
            .as_ref()
            .is_some_and(|build| !build.steps.is_empty())
        {
            return Err(ManifestV1Error::Unsupported {
                feature: "[[build.steps]]",
                why: "a build output has no name and no guest placement in this build, so its \
                      projection could not be committed",
            });
        }
        if !self.state.is_empty() {
            return Err(ManifestV1Error::Unsupported {
                feature: "[state.<name>]",
                why: "RFC §8.3 refuses a RUNNING capture of a workload with external state — it \
                      needs `workload_idle`, which is a separate lifecycle",
            });
        }
        let Some(web) = &self.web else {
            return Err(ManifestV1Error::Missing { field: "[web]" });
        };
        let _ = web;
        if self.seal_at.is_none() {
            return Err(ManifestV1Error::Missing {
                field: "[seal_at].command",
            });
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const MINIMAL: &str = r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python", "-m", "app"]

[web]
port = 8080
bind = "0.0.0.0"

[seal_at]
command = ["curl", "-fsS", "http://127.0.0.1:8080/health"]
"#;

    fn parse(text: &str) -> Result<CapsuleManifestV1, ManifestV1Error> {
        CapsuleManifestV1::from_toml(text)
    }

    #[test]
    fn the_minimal_step_four_manifest_parses_and_qualifies() {
        let manifest = parse(MINIMAL).expect("parses");
        assert_eq!(manifest.run.command, ["python", "-m", "app"]);
        assert_eq!(manifest.web.as_ref().unwrap().port, 8080);
        assert_eq!(manifest.web.as_ref().unwrap().bind, "0.0.0.0");
        manifest
            .validate_for_interactive_capture()
            .expect("qualifies for the Step-4 subset");
    }

    /// The command is an argv, and argument boundaries survive verbatim —
    /// including an argument containing a space and an empty one.
    ///
    /// This is the difference v0.3 cannot express: it carries a single shell
    /// string, which has to be re-split by something, and whatever re-splits it
    /// is a second opinion about what the author meant.
    #[test]
    fn argument_boundaries_are_preserved_exactly() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python", "-m", "app", "--flag=a b", "", "--last"]

[web]
port = 8080
bind = "127.0.0.1"
"#,
        )
        .expect("parses");
        assert_eq!(
            manifest.run.command,
            ["python", "-m", "app", "--flag=a b", "", "--last"],
            "an argument with a space is ONE argument, and an empty argument is a real one"
        );
    }

    /// A shell is available by asking for one — and then it is visible in the
    /// identity as what it is, rather than implied.
    #[test]
    fn an_explicit_shell_is_allowed_and_stays_visible() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["sh", "-lc", "exec python -m app"]
"#,
        )
        .expect("parses");
        assert_eq!(manifest.run.command[0], "sh");
    }

    #[test]
    fn a_command_that_is_a_string_is_refused() {
        let error = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = "python -m app"
"#,
        )
        .expect_err("a shell string is not a v1 command");
        assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
    }

    #[test]
    fn an_empty_command_and_an_empty_program_are_refused() {
        for command in ["[]", r#"["", "app"]"#] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = {command}
"#
            ))
            .expect_err("must refuse {command}");
            assert!(
                matches!(
                    error,
                    ManifestV1Error::Invalid {
                        field: "run.command",
                        ..
                    }
                ),
                "{error}"
            );
        }
    }

    /// v0.3 does not become v1 by being read by this parser.
    #[test]
    fn a_v03_manifest_is_refused_by_the_v1_parser() {
        let error = parse(
            r#"
schema_version = "0.3"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]
"#,
        )
        .expect_err("0.3 is not v1");
        match error {
            ManifestV1Error::RequiresManifestV1 { found } => assert_eq!(found, "0.3"),
            other => panic!("expected RequiresManifestV1, got {other}"),
        }
    }

    /// The stable code the api and the wizard key on, raised at the entrance of
    /// a mint path rather than partway through an observation.
    #[test]
    fn the_mint_gate_names_what_it_found() {
        assert!(require_manifest_v1("1").is_ok());
        let error = require_manifest_v1("0.3").expect_err("refuses");
        assert!(
            error
                .to_string()
                .contains(EXECUTION_IDENTITY_REQUIRES_MANIFEST_V1),
            "{error}"
        );
        assert!(error.to_string().contains("\"0.3\""), "{error}");
    }

    /// A typo is an error, not a silently-ignored intent.
    #[test]
    fn an_unknown_field_is_refused_rather_than_ignored() {
        for extra in ["prot = 8080", "commnd = [\"x\"]"] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"
{extra}

[run]
command = ["python"]
"#
            ))
            .expect_err("unknown field");
            assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
        }
    }

    /// `bind` has no default. `0.0.0.0` is a fixture value throughout the tree,
    /// and ADR-015 §2 forbids promoting one to a normative default — an author
    /// who wants every interface says so.
    #[test]
    fn web_requires_an_explicit_bind() {
        let error = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[web]
port = 8080
"#,
        )
        .expect_err("bind has no default");
        assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
    }

    #[test]
    fn a_zero_port_is_refused() {
        let error = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[web]
port = 0
bind = "0.0.0.0"
"#,
        )
        .expect_err("port 0 is never a declared surface");
        assert!(
            matches!(
                error,
                ManifestV1Error::Invalid {
                    field: "web.port",
                    ..
                }
            ),
            "{error}"
        );
    }

    /// Every state field is authored — `access` in particular, which v0.3 has no
    /// counterpart for at all.
    #[test]
    fn state_declares_mount_access_schema_and_snapshot() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[state.data]
mount = "/data"
access = "read-write"
schema = "demo.data/v1"
snapshot = "exclude"
"#,
        )
        .expect("parses");
        let state = &manifest.state["data"];
        assert_eq!(state.mount, "/data");
        assert_eq!(state.access, StateAccessV1::ReadWrite);
        assert_eq!(state.schema, "demo.data/v1");
        assert_eq!(state.snapshot, SnapshotDispositionV1::Exclude);
    }

    #[test]
    fn a_state_block_missing_any_field_is_refused() {
        for missing in [
            r#"access = "read-write"
schema = "s"
snapshot = "exclude""#,
            r#"mount = "/data"
schema = "s"
snapshot = "exclude""#,
            r#"mount = "/data"
access = "read-write"
snapshot = "exclude""#,
            r#"mount = "/data"
access = "read-write"
schema = "s""#,
        ] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[state.data]
{missing}
"#
            ))
            .expect_err("every state field is required");
            assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
        }
    }

    #[test]
    fn a_relative_or_traversing_state_mount_is_refused() {
        for mount in ["data", "/data/../etc", "/data/"] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[state.data]
mount = "{mount}"
access = "read-only"
schema = "s"
snapshot = "exclude"
"#
            ))
            .expect_err("must refuse {mount}");
            assert!(
                matches!(
                    error,
                    ManifestV1Error::Invalid {
                        field: "state.<name>.mount",
                        ..
                    }
                ),
                "{mount}: {error}"
            );
        }
    }

    /// Outside the Step-4 subset is a REFUSAL BY NAME, not an approximation —
    /// and not a parse error either, because these are perfectly good capsules.
    #[test]
    fn features_outside_the_step_four_subset_are_refused_by_name() {
        let cases: [(&str, &str); 3] = [
            (
                r#"
[tools]
python = "3.12""#,
                "[tools]",
            ),
            (
                r#"
[[build.steps]]
command = ["make"]"#,
                "[[build.steps]]",
            ),
            (
                r#"
[state.data]
mount = "/data"
access = "read-write"
schema = "s"
snapshot = "exclude""#,
                "[state.<name>]",
            ),
        ];
        for (extra, feature) in cases {
            let manifest = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[web]
port = 8080
bind = "0.0.0.0"

[seal_at]
command = ["true"]
{extra}
"#
            ))
            .expect("it PARSES — it is a valid v1 manifest");
            let error = manifest
                .validate_for_interactive_capture()
                .expect_err("outside the subset");
            match error {
                ManifestV1Error::Unsupported { feature: named, .. } => {
                    assert_eq!(named, feature)
                }
                other => panic!("expected Unsupported({feature}), got {other}"),
            }
        }
    }

    /// Step 4 cannot accept a candidate without an acceptance program, and
    /// cannot make a preview reachable without a surface.
    #[test]
    fn the_step_four_subset_requires_web_and_seal_at() {
        let without_seal = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[web]
port = 8080
bind = "0.0.0.0"
"#,
        )
        .expect("parses");
        assert!(matches!(
            without_seal.validate_for_interactive_capture(),
            Err(ManifestV1Error::Missing {
                field: "[seal_at].command"
            })
        ));

        let without_web = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[seal_at]
command = ["true"]
"#,
        )
        .expect("parses");
        assert!(matches!(
            without_web.validate_for_interactive_capture(),
            Err(ManifestV1Error::Missing { field: "[web]" })
        ));
    }

    #[test]
    fn a_seal_at_timeout_outside_the_policy_ceiling_is_refused() {
        for seconds in [0, MAX_SEAL_AT_TIMEOUT_SECONDS + 1] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[seal_at]
command = ["true"]
timeout_seconds = {seconds}
"#
            ))
            .expect_err("outside the ceiling");
            assert!(
                matches!(
                    error,
                    ManifestV1Error::Invalid {
                        field: "seal_at.timeout_seconds",
                        ..
                    }
                ),
                "{seconds}: {error}"
            );
        }
    }

    /// A v1 manifest round-trips through its own serializer without acquiring
    /// or losing a field — the property that keeps a written manifest readable
    /// by the same parser.
    #[test]
    fn a_manifest_round_trips() {
        let manifest = parse(MINIMAL).expect("parses");
        let text = toml::to_string(&manifest).expect("serialize");
        assert_eq!(
            CapsuleManifestV1::from_toml(&text).expect("reparse"),
            manifest
        );
    }
}
