//! `schema_version = "1"` — the authoring surface an Execution Identity may be
//! minted from (RFC §6, ADR-015).
//!
//! # Why this is a separate type
//!
//! It is NOT a variant of the v0.3 [`CapsuleManifest`](super::manifest::CapsuleManifest),
//! and there is deliberately no conversion between them. v0.3 cannot express
//! three things v1 identity requires — a guest bind address, an external
//! state's access mode, and a command as an argv rather than a shell string —
//! so any conversion would have to invent them. ADR-015's rule is that a
//! contract is never generated by filling v0.3's ambiguous values with
//! defaults, and the cheapest way to keep that rule is to make the conversion
//! impossible to write by accident.
//!
//! v0.3 keeps working for `run` and `build`, unchanged. It simply never mints.
//!
//! # The authored command is an argv
//!
//! ```toml
//! [run]
//! command = ["python", "-m", "app", "--flag=a b"]
//! ```
//!
//! Four arguments, the last containing a space. There is no string for a
//! quoting mistake to live in, and no implicit shell — RFC §6.1 requires
//! argument boundaries to be preserved exactly, and a shell is available only
//! by asking for one (`["sh", "-lc", "…"]`), which is then visible in the
//! identity as what it is.
//!
//! This is the AUTHORED command. The resolved `launch.argv` recorded in an
//! Execution Contract is what the runner actually starts, which may legitimately
//! wrap it — see ADR-015 §3.
//!
//! # Environment: a value, or a name, never a guess
//!
//! The Execution Contract has exactly two places a variable can live:
//! `launch.environment` (non-secret values, each committed by digest) and
//! `launch.secret_bindings` (names only — a secret VALUE is never
//! identity-bearing, RFC §4.3). So the authoring surface has exactly two too:
//!
//! ```toml
//! [env]                  # authored non-secret values -> launch.environment
//! NODE_ENV = "production"
//!
//! [config.API_KEY]       # supplied at launch
//! kind = "secret"        # -> launch.secret_bindings (the NAME only)
//! required = true
//! ```
//!
//! `kind` and `required` are both explicit. v0.3's `ConfigField` has no
//! `required` field at all and its `ConfigKind` DEFAULTS to `secret`, so a
//! legacy capsule's whole env surface classifies as secret — that default is
//! not reused here, and a v1 config field that omits either is refused rather
//! than assumed.
//!
//! # Fail closed, and refuse rather than approximate
//!
//! Unknown fields, duplicate keys and ambiguous defaults are rejected. Features
//! outside the Step-4 vertical subset (ADR-015 §7) are refused BY NAME rather
//! than silently ignored or approximated: a capsule that declares services or
//! dependencies is not a capsule this build can mint an identity for, and
//! saying so is more useful than minting an identity that omits them.

use std::collections::BTreeMap;
use std::path::Path;

use ignore::gitignore::{Gitignore, GitignoreBuilder};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;
use url::Url;

/// The only schema version that may mint an Execution Identity.
pub const MANIFEST_SCHEMA_V1: &str = "1";

/// Ceiling for `seal_at.timeout_seconds`, shared with the v0.3 table so one
/// capsule cannot get two answers by changing schema version.
pub use super::ready_state::MAX_SEAL_AT_TIMEOUT_SECONDS;

/// Why a v1 manifest was refused. Every variant is a refusal to proceed, never
/// a value to substitute.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum ManifestV1Error {
    #[error("capsule.toml is not valid TOML: {0}")]
    Toml(String),
    /// The stable code the wire and the CLI both use for "this manifest cannot
    /// mint" (ADR-015 §6.4).
    #[error(
        "execution_identity_requires_manifest_v1: an Execution Identity can only be minted from \
         schema_version = \"1\" (found {found:?}). v0.3 keeps working for run and build; it is \
         not converted, because it cannot express the guest bind address, an external state's \
         access mode, or a command as an argv."
    )]
    RequiresManifestV1 { found: String },
    #[error("{field} is required in a v1 manifest and has no default")]
    Missing { field: &'static str },
    #[error("{field} is invalid: {reason}")]
    Invalid { field: &'static str, reason: String },
    /// A feature outside the Step-4 vertical subset. Named, so the author is
    /// told what to remove rather than left to guess why the identity is wrong.
    #[error(
        "{feature} is not supported by this build's v1 subset (ADR-015 §7): {why}. \
         Use schema_version = \"0.3\" for it — that path is unchanged, it simply does not mint \
         an Execution Identity."
    )]
    Unsupported {
        feature: &'static str,
        why: &'static str,
    },
}

/// The stable error code, for the api and the wizard to key on.
pub const EXECUTION_IDENTITY_REQUIRES_MANIFEST_V1: &str = "execution_identity_requires_manifest_v1";

/// The gate at the entrance of any mint path (ADR-015 §6.4).
///
/// Raised HERE — at the entrance — and never partway through an observation, so
/// the refusal is one behaviour in one place rather than a family of
/// similar-looking failures scattered across the measurement producers.
pub fn require_manifest_v1(schema_version: &str) -> Result<(), ManifestV1Error> {
    if schema_version.trim() == MANIFEST_SCHEMA_V1 {
        return Ok(());
    }
    Err(ManifestV1Error::RequiresManifestV1 {
        found: schema_version.to_string(),
    })
}

/// A v1 `capsule.toml`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CapsuleManifestV1 {
    /// Must be exactly `"1"`. Checked at parse, not at use.
    pub schema_version: String,
    pub name: String,
    pub version: String,

    /// `[source]` — the deterministic source-selection policy used before the
    /// source closure is computed. The default preserves the pre-unified-v1
    /// behavior for already-authored manifests.
    #[serde(default, skip_serializing_if = "SourceSelectionV1::is_default")]
    pub source: SourceSelectionV1,

    /// `[metadata]` — Store-facing authored intent. It is part of the
    /// normalized manifest digest even though it does not alter launch.
    #[serde(default, skip_serializing_if = "MetadataV1::is_empty")]
    pub metadata: MetadataV1,

    /// `[tools]` — pinned tool versions, by name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub tools: BTreeMap<String, String>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub build: Option<BuildV1>,

    /// `[run]` — how the workload is started.
    pub run: RunV1,

    /// `[web]` — the guest-facing surface, when the capsule serves one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub web: Option<WebV1>,

    /// `[seal_at]` — the acceptance program. Required to capture interactively;
    /// see [`Self::validate_for_interactive_capture`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seal_at: Option<SealAtV1>,

    /// `[env]` — authored non-secret values. Identity-bearing, so they are
    /// values here rather than a schema for values.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub env: BTreeMap<String, String>,

    /// `[config.<NAME>]` — variables supplied at launch, not at authoring.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub config: BTreeMap<String, ConfigFieldV1>,

    /// `[state.<name>]` — external state, fully declared.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub state: BTreeMap<String, StateV1>,

    /// `[outputs]` — declared Materialization output contracts. Additive:
    /// absent means snapshot-only. A `dist/` directory never selects the
    /// static web lane on its own; only an authored `[outputs.static_web]`
    /// section declares it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outputs: Option<OutputsV1>,
}

pub const SOURCE_FILTER_POLICY_VERSION_V1: &str = "ato-source-filter/v1";
pub const MAX_SOURCE_IGNORE_PATTERNS_V1: usize = 256;
pub const MAX_SOURCE_IGNORE_PATTERN_BYTES_V1: usize = 1024;
pub const MAX_SOURCE_IGNORE_TOTAL_BYTES_V1: usize = 64 * 1024;

/// Safety exclusions are policy, not author intent. A later manifest negation
/// can never re-include one of these paths.
pub const SYSTEM_SOURCE_IGNORE_V1: &[&str] = &[
    ".git/**",
    ".env",
    ".env.*",
    "**/*.pem",
    "**/*.key",
    "**/id_rsa",
    "**/id_ed25519",
    "**/.aws/**",
    "**/.ssh/**",
];

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceSelectionV1 {
    #[serde(default = "default_source_root")]
    pub root: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub ignore: Vec<String>,
}

impl Default for SourceSelectionV1 {
    fn default() -> Self {
        Self {
            root: default_source_root(),
            ignore: Vec::new(),
        }
    }
}

impl SourceSelectionV1 {
    fn is_default(&self) -> bool {
        self.root == "." && self.ignore.is_empty()
    }
}

fn default_source_root() -> String {
    ".".to_string()
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MetadataV1 {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub short_description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub store: Option<StoreMetadataV1>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assets: Option<MetadataAssetsV1>,
}

impl MetadataV1 {
    fn is_empty(&self) -> bool {
        self == &Self::default()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StoreMetadataV1 {
    pub category: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subcategory: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MetadataAssetsV1 {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<AssetLocatorV1>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub banner: Option<AssetLocatorV1>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetLocatorV1 {
    Path(AssetPathLocatorV1),
    Url(AssetUrlLocatorV1),
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AssetPathLocatorV1 {
    pub path: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AssetUrlLocatorV1 {
    pub url: String,
    pub content_digest: String,
    pub artifact_ref: String,
    pub media_type: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin_url: Option<String>,
}

/// One launch-supplied variable. BOTH fields are explicit.
///
/// v0.3's equivalent has no `required` at all and defaults its kind to
/// `secret`, which silently reclassifies a legacy capsule's entire env surface.
/// Neither default is inherited: a v1 field that omits either is refused, so
/// the classification is always something the author said.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigFieldV1 {
    pub kind: ConfigKindV1,
    pub required: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ConfigKindV1 {
    /// The value never enters identity; only the NAME is bound (RFC §4.3).
    Secret,
    /// A non-secret value supplied at launch. Identity-bearing, but not known
    /// at authoring time — see the subset refusal in
    /// [`CapsuleManifestV1::validate_for_interactive_capture`].
    String,
    Number,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BuildV1 {
    /// `[[build.steps]]` — ordered. Each step's `command` is an argv.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub steps: Vec<BuildStepV1>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BuildStepV1 {
    /// Exact argv. No implicit shell.
    pub command: Vec<String>,
}

/// `[outputs]` — the Materialization output contracts an author declares.
///
/// The presence of a built directory (e.g. a Vite `dist/`) never selects an
/// output lane; only an authored section here does. Absent `[outputs]` keeps
/// today's snapshot-only behavior unchanged.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OutputsV1 {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub static_web: Option<StaticWebOutputV1>,
}

/// `[outputs.static_web]` — an explicit Static Web Materialization contract.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StaticWebOutputV1 {
    /// Non-empty relative path to the built static output root inside the
    /// guest image (e.g. `dist` or `srv/app/dist`). Validated at Build
    /// Attempt time against the built image; parse-time only checks path shape.
    pub root: String,
    /// Entry document, normalized relative to `root` (e.g. `index.html`).
    pub entry_path: String,
    /// Whether unknown GET paths fall back to the entry document (SPA).
    #[serde(default = "default_spa_fallback")]
    pub spa_fallback: bool,
    /// Exact public HTTPS/WSS origins the built app may connect to. Sorted
    /// ASCII order, no duplicates. Frame ancestors are fixed by the v1
    /// contract and are not authorable.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub connect_src: Vec<String>,
}

fn default_spa_fallback() -> bool {
    true
}

impl StaticWebOutputV1 {
    /// Validates the authored static web output contract. The existence of
    /// `root`/`entry_path` inside a built image is deliberately NOT checked
    /// here — that is a Build Attempt-time fact, resolved against the built
    /// image by the producer.
    pub fn validate(&self) -> Result<(), ManifestV1Error> {
        validate_static_web_root(&self.root)?;
        validate_source_relative_path("outputs.static_web.entry_path", &self.entry_path, false)?;
        for origin in &self.connect_src {
            crate::contract::static_web_manifest::validate_connect_source(origin).map_err(
                |error| ManifestV1Error::Invalid {
                    field: "outputs.static_web.connect_src[]",
                    reason: format!("{origin:?} is not a public https/wss origin: {error}"),
                },
            )?;
        }
        let mut sorted = self.connect_src.clone();
        sorted.sort_unstable();
        if sorted != self.connect_src {
            return Err(ManifestV1Error::Invalid {
                field: "outputs.static_web.connect_src[]",
                reason: "must be sorted in ASCII dictionary order without duplicates".to_string(),
            });
        }
        if sorted.windows(2).any(|pair| pair[0] == pair[1]) {
            return Err(ManifestV1Error::Invalid {
                field: "outputs.static_web.connect_src[]",
                reason: "must not contain a duplicate origin".to_string(),
            });
        }
        Ok(())
    }
}

fn validate_static_web_root(value: &str) -> Result<(), ManifestV1Error> {
    if value.is_empty()
        || value.starts_with('/')
        || value.contains('\\')
        || value.contains('\0')
        || value.contains('%')
        || value
            .split('/')
            .any(|segment| segment.is_empty() || segment == "." || segment == "..")
    {
        return Err(ManifestV1Error::Invalid {
            field: "outputs.static_web.root",
            reason:
                "must be a non-empty relative path without '.', '..', empty segments, backslashes, percent signs, or a leading slash"
                    .to_string(),
        });
    }
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RunV1 {
    /// Exact argv. No implicit shell (RFC §6.1).
    pub command: Vec<String>,
}

/// `[web]`. Both fields are authored — neither has a default.
///
/// `bind` in particular: `0.0.0.0` appears throughout the tree as a test-fixture
/// value, and ADR-015 §2 forbids promoting a fixture value to a normative
/// default. An author who wants every interface says so.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WebV1 {
    pub port: u16,
    pub bind: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SealAtV1 {
    /// Exact argv, run against a disposable restore. Exit 0 accepts.
    pub command: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<u32>,
}

/// `[state.<name>]`. Every field is authored: this is the declaration an
/// Execution Contract's `external_state` entry is built from, and v0.3 has no
/// counterpart for `access` at all.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StateV1 {
    /// Absolute guest path.
    pub mount: String,
    pub access: StateAccessV1,
    /// Schema identity. The consumer gate is exact string equality with no
    /// migration, so there is no default that could be safely assumed.
    pub schema: String,
    pub snapshot: SnapshotDispositionV1,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum StateAccessV1 {
    ReadOnly,
    ReadWrite,
}

/// Single-valued in v1, and still stated explicitly rather than implied: an
/// author reading the file should see that state is excluded from the snapshot,
/// not have to know it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SnapshotDispositionV1 {
    Exclude,
}

/// An authored argv, checked the same way everywhere it appears.
///
/// `argv[0]` must be non-empty because it is the program; LATER arguments may
/// be empty, because an empty argument is a real argument and dropping it would
/// change the command. No argument may contain a NUL, which no exec boundary
/// can carry.
fn validate_argv(field: &'static str, argv: &[String]) -> Result<(), ManifestV1Error> {
    if argv.is_empty() {
        return Err(ManifestV1Error::Invalid {
            field,
            reason: "must be a non-empty argv array; a v1 command is never a shell string"
                .to_string(),
        });
    }
    if argv[0].trim().is_empty() {
        return Err(ManifestV1Error::Invalid {
            field,
            reason: "argv[0] is the program and must not be empty".to_string(),
        });
    }
    if let Some(index) = argv.iter().position(|argument| argument.contains('\0')) {
        return Err(ManifestV1Error::Invalid {
            field,
            reason: format!("argv[{index}] must not contain a NUL byte"),
        });
    }
    Ok(())
}

/// A POSIX environment variable name: `[A-Za-z_][A-Za-z0-9_]*`.
fn is_env_var_name(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(first) if first.is_ascii_alphabetic() || first == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// The workspace's secret-name heuristic, kept in ONE place: this delegates to
/// the contract's classifier so the authoring surface and the identity gate can
/// never disagree about which names are secret-bearing.
fn looks_secret(name: &str) -> bool {
    crate::execution_contract_finalize::is_sensitive_env_key(name)
}

fn validate_source_relative_path(
    field: &'static str,
    value: &str,
    allow_root: bool,
) -> Result<(), ManifestV1Error> {
    if value == "." {
        return if allow_root {
            Ok(())
        } else {
            Err(ManifestV1Error::Invalid {
                field,
                reason: "must name a file below the source root".to_string(),
            })
        };
    }
    if value.is_empty()
        || value.starts_with('/')
        || value.ends_with('/')
        || value.contains('\\')
        || value.contains('\0')
        || value.contains('%')
        || value
            .split('/')
            .any(|segment| segment.is_empty() || segment == "." || segment == "..")
    {
        return Err(ManifestV1Error::Invalid {
            field,
            reason: "must be a normalized source-relative path without '.', '..', empty segments, backslashes, percent signs, or a leading slash".to_string(),
        });
    }
    Ok(())
}

fn validate_ignore_pattern(pattern: &str) -> Result<(), ManifestV1Error> {
    let body = pattern.strip_prefix('!').unwrap_or(pattern);
    let body = body.strip_prefix('/').unwrap_or(body);
    if body.is_empty()
        || pattern.contains('\\')
        || pattern.contains('\0')
        || pattern.starts_with("//")
        || body.split('/').any(|segment| segment == "..")
    {
        return Err(ManifestV1Error::Invalid {
            field: "source.ignore[]",
            reason: format!(
                "{pattern:?} is not a supported source-root-relative gitignore pattern"
            ),
        });
    }
    Ok(())
}

fn build_ignore_matcher(
    patterns: impl IntoIterator<Item = impl AsRef<str>>,
) -> Result<Gitignore, ManifestV1Error> {
    let mut builder = GitignoreBuilder::new(".");
    for pattern in patterns {
        let pattern = pattern.as_ref();
        builder
            .add_line(None, pattern)
            .map_err(|error| ManifestV1Error::Invalid {
                field: "source.ignore[]",
                reason: format!("{pattern:?}: {error}"),
            })?;
    }
    builder.build().map_err(|error| ManifestV1Error::Invalid {
        field: "source.ignore[]",
        reason: error.to_string(),
    })
}

fn is_sha256_digest(value: &str) -> bool {
    value.strip_prefix("sha256:").is_some_and(|hex| {
        hex.len() == 64
            && hex
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
    })
}

impl CapsuleManifestV1 {
    /// Parse and validate. There is no lenient mode: a manifest that does not
    /// validate is not a v1 manifest.
    pub fn from_toml(text: &str) -> Result<Self, ManifestV1Error> {
        // `deny_unknown_fields` throughout plus toml's own duplicate-key
        // rejection is what makes the accepted spelling single-valued: a typo'd
        // key is an error rather than a silently-ignored intent.
        let manifest: Self =
            toml::from_str(text).map_err(|error| ManifestV1Error::Toml(error.to_string()))?;
        manifest.validate()?;
        Ok(manifest)
    }

    /// SHA-256 over the canonical JSON form of the normalized v1 manifest.
    /// Defaults are expanded by deserialization before this is computed, so
    /// omitted and explicitly-defaulted source/metadata sections agree.
    pub fn normalized_digest(&self) -> Result<String, ManifestV1Error> {
        self.validate()?;
        let bytes = serde_jcs::to_vec(self).map_err(|error| ManifestV1Error::Invalid {
            field: "capsule.toml",
            reason: format!("failed to canonicalize the normalized manifest: {error}"),
        })?;
        Ok(format!("sha256:{}", hex::encode(Sha256::digest(bytes))))
    }

    /// Whether a source-relative path survives both the immutable system
    /// safety policy and the manifest's last-match-wins ignore rules.
    pub fn source_path_is_included(
        &self,
        relative_path: &str,
        is_dir: bool,
    ) -> Result<bool, ManifestV1Error> {
        validate_source_relative_path("source path", relative_path, false)?;
        let path = Path::new(relative_path);
        let system = build_ignore_matcher(SYSTEM_SOURCE_IGNORE_V1)?;
        if system.matched_path_or_any_parents(path, is_dir).is_ignore() {
            return Ok(false);
        }
        let authored = build_ignore_matcher(&self.source.ignore)?;
        Ok(!authored
            .matched_path_or_any_parents(path, is_dir)
            .is_ignore())
    }

    pub fn validate(&self) -> Result<(), ManifestV1Error> {
        require_manifest_v1(&self.schema_version)?;
        for (field, value) in [("name", &self.name), ("version", &self.version)] {
            if value.trim().is_empty() {
                return Err(ManifestV1Error::Missing { field });
            }
        }

        validate_source_relative_path("source.root", &self.source.root, true)?;
        if self.source.ignore.len() > MAX_SOURCE_IGNORE_PATTERNS_V1 {
            return Err(ManifestV1Error::Invalid {
                field: "source.ignore",
                reason: format!(
                    "contains {} patterns; the limit is {MAX_SOURCE_IGNORE_PATTERNS_V1}",
                    self.source.ignore.len()
                ),
            });
        }
        let total_ignore_bytes = self
            .source
            .ignore
            .iter()
            .try_fold(0usize, |total, pattern| {
                if pattern.len() > MAX_SOURCE_IGNORE_PATTERN_BYTES_V1 {
                    return Err(ManifestV1Error::Invalid {
                        field: "source.ignore[]",
                        reason: format!(
                            "pattern is {} bytes; the limit is {MAX_SOURCE_IGNORE_PATTERN_BYTES_V1}",
                            pattern.len()
                        ),
                    });
                }
                validate_ignore_pattern(pattern)?;
                Ok(total + pattern.len())
            })?;
        if total_ignore_bytes > MAX_SOURCE_IGNORE_TOTAL_BYTES_V1 {
            return Err(ManifestV1Error::Invalid {
                field: "source.ignore",
                reason: format!(
                    "contains {total_ignore_bytes} bytes; the limit is {MAX_SOURCE_IGNORE_TOTAL_BYTES_V1}"
                ),
            });
        }
        // Compile once during validation so malformed glob syntax is refused
        // before any source walk starts.
        build_ignore_matcher(&self.source.ignore)?;

        if let Some(store) = &self.metadata.store {
            if store.category.trim().is_empty() {
                return Err(ManifestV1Error::Missing {
                    field: "metadata.store.category",
                });
            }
            if store
                .subcategory
                .as_deref()
                .is_some_and(|value| value.trim().is_empty())
            {
                return Err(ManifestV1Error::Invalid {
                    field: "metadata.store.subcategory",
                    reason: "must not be empty when present".to_string(),
                });
            }
        }
        if self.metadata.tags.iter().any(|tag| tag.trim().is_empty()) {
            return Err(ManifestV1Error::Invalid {
                field: "metadata.tags[]",
                reason: "must not contain empty tags".to_string(),
            });
        }
        if let Some(assets) = &self.metadata.assets {
            for (field, locator) in [
                ("metadata.assets.icon", assets.icon.as_ref()),
                ("metadata.assets.banner", assets.banner.as_ref()),
            ] {
                match locator {
                    Some(AssetLocatorV1::Path(path)) => {
                        validate_source_relative_path(field, &path.path, false)?;
                        if !self.source_path_is_included(&path.path, false)? {
                            return Err(ManifestV1Error::Invalid {
                                field,
                                reason: format!(
                                    "referenced path {:?} is excluded by the effective source policy",
                                    path.path
                                ),
                            });
                        }
                    }
                    Some(AssetLocatorV1::Url(url)) => {
                        let parsed =
                            Url::parse(&url.url).map_err(|error| ManifestV1Error::Invalid {
                                field,
                                reason: format!("must be an HTTPS URL: {error}"),
                            })?;
                        if parsed.scheme() != "https"
                            || parsed.host_str().is_none()
                            || !parsed.username().is_empty()
                            || parsed.password().is_some()
                        {
                            return Err(ManifestV1Error::Invalid {
                                field,
                                reason: "must be a credential-free HTTPS URL with a host"
                                    .to_string(),
                            });
                        }
                        if !is_sha256_digest(&url.content_digest) {
                            return Err(ManifestV1Error::Invalid {
                                field,
                                reason: "content_digest must be sha256:<64 lowercase hex>"
                                    .to_string(),
                            });
                        }
                        let digest_hex = &url.content_digest["sha256:".len()..];
                        if url.artifact_ref != format!("ato-asset://sha256/{digest_hex}") {
                            return Err(ManifestV1Error::Invalid {
                                field,
                                reason: "artifact_ref must match content_digest exactly"
                                    .to_string(),
                            });
                        }
                        if !matches!(
                            url.media_type.as_str(),
                            "image/png" | "image/jpeg" | "image/webp"
                        ) {
                            return Err(ManifestV1Error::Invalid {
                                field,
                                reason: "media_type must be image/png, image/jpeg, or image/webp"
                                    .to_string(),
                            });
                        }
                        if let Some(origin_url) = &url.origin_url {
                            let origin = Url::parse(origin_url).map_err(|error| {
                                ManifestV1Error::Invalid {
                                    field,
                                    reason: format!("origin_url must be HTTPS: {error}"),
                                }
                            })?;
                            if origin.scheme() != "https"
                                || origin.host_str().is_none()
                                || !origin.username().is_empty()
                                || origin.password().is_some()
                            {
                                return Err(ManifestV1Error::Invalid {
                                    field,
                                    reason: "origin_url must be a credential-free HTTPS URL"
                                        .to_string(),
                                });
                            }
                        }
                    }
                    None => {}
                }
            }
        }

        validate_argv("run.command", &self.run.command)?;
        if let Some(build) = &self.build {
            for (index, step) in build.steps.iter().enumerate() {
                validate_argv("build.steps[].command", &step.command).map_err(
                    |error| match error {
                        ManifestV1Error::Invalid { reason, .. } => ManifestV1Error::Invalid {
                            field: "build.steps[].command",
                            reason: format!("step {index}: {reason}"),
                        },
                        other => other,
                    },
                )?;
            }
        }

        if let Some(web) = &self.web {
            if web.port == 0 {
                return Err(ManifestV1Error::Invalid {
                    field: "web.port",
                    reason: "must be 1..=65535".to_string(),
                });
            }
            if web.bind.trim().is_empty() {
                return Err(ManifestV1Error::Missing { field: "web.bind" });
            }
        }

        if let Some(seal_at) = &self.seal_at {
            validate_argv("seal_at.command", &seal_at.command)?;
            match seal_at.timeout_seconds {
                None => {}
                Some(seconds) if (1..=MAX_SEAL_AT_TIMEOUT_SECONDS).contains(&seconds) => {}
                Some(seconds) => {
                    return Err(ManifestV1Error::Invalid {
                        field: "seal_at.timeout_seconds",
                        reason: format!(
                            "must be 1..={MAX_SEAL_AT_TIMEOUT_SECONDS} seconds, got {seconds}"
                        ),
                    });
                }
            }
        }

        // A variable is either an authored non-secret VALUE or a launch-supplied
        // NAME. Both is a contradiction the Execution Contract refuses at
        // generation time (`EnvironmentNameIsSecretBinding`); refusing it here
        // as well costs nothing and tells the author which line to change.
        for name in self.env.keys() {
            if !is_env_var_name(name) {
                return Err(ManifestV1Error::Invalid {
                    field: "env.<NAME>",
                    reason: format!("{name:?} is not a POSIX environment variable name"),
                });
            }
            // The heuristic is defence in depth, not the boundary — but a
            // secret-looking name authored as a plain VALUE would be refused by
            // the contract later, and naming it here says which line to fix.
            if looks_secret(name) {
                return Err(ManifestV1Error::Invalid {
                    field: "env.<NAME>",
                    reason: format!(
                        "{name:?} is secret-bearing; a secret value is never identity-bearing \
                         (RFC §4.3) — declare it as [config.{name}] with kind = \"secret\" so \
                         only the name is bound"
                    ),
                });
            }
            if let Some(field) = self.config.get(name) {
                return Err(ManifestV1Error::Invalid {
                    field: "config.<NAME>",
                    reason: format!(
                        "{name:?} is declared both as an authored [env] value and as a \
                         [config.{name}] ({:?}) — a variable is either a value or a \
                         launch-supplied name, never both",
                        field.kind
                    ),
                });
            }
        }
        for name in self.config.keys() {
            if !is_env_var_name(name) {
                return Err(ManifestV1Error::Invalid {
                    field: "config.<NAME>",
                    reason: format!("{name:?} is not a POSIX environment variable name"),
                });
            }
        }

        for (name, state) in &self.state {
            if name.trim().is_empty() {
                return Err(ManifestV1Error::Missing {
                    field: "state.<name>",
                });
            }
            if !state.mount.starts_with('/')
                || state.mount.contains("/../")
                || state.mount.ends_with("/..")
                || state.mount.ends_with('/')
            {
                return Err(ManifestV1Error::Invalid {
                    field: "state.<name>.mount",
                    reason: format!(
                        "{:?} must be an absolute guest path with no '..' segment and no trailing slash",
                        state.mount
                    ),
                });
            }
            if state.schema.trim().is_empty() {
                return Err(ManifestV1Error::Missing {
                    field: "state.<name>.schema",
                });
            }
        }

        if let Some(static_web) = self
            .outputs
            .as_ref()
            .and_then(|outputs| outputs.static_web.as_ref())
        {
            static_web.validate()?;
        }
        Ok(())
    }

    /// The Step-4 vertical subset (ADR-015 §7).
    ///
    /// Separate from [`Self::validate`] because these are not malformed
    /// manifests — they are perfectly good capsules this build cannot yet mint
    /// an identity for. A `run`/`build` caller must not be blocked by them.
    pub fn validate_for_interactive_capture(&self) -> Result<(), ManifestV1Error> {
        self.validate()?;

        if !self.tools.is_empty() {
            return Err(ManifestV1Error::Unsupported {
                feature: "[tools]",
                why: "a pinned tool is a dependency, and per-dependency derivation and output \
                      digests have no producer yet, so its identity could not be measured",
            });
        }
        if self
            .build
            .as_ref()
            .is_some_and(|build| !build.steps.is_empty())
            && self
                .outputs
                .as_ref()
                .and_then(|outputs| outputs.static_web.as_ref())
                .is_none()
        {
            return Err(ManifestV1Error::Unsupported {
                feature: "[[build.steps]]",
                why: "this build has no declared guest output root, so its projection could not \
                      be committed",
            });
        }
        if !self.state.is_empty() {
            return Err(ManifestV1Error::Unsupported {
                feature: "[state.<name>]",
                why: "RFC §8.3 refuses a RUNNING capture of a workload with external state — it \
                      needs `workload_idle`, which is a separate lifecycle",
            });
        }
        // A non-secret variable supplied at LAUNCH has a value that is
        // identity-bearing and unknown at authoring time. The contract has
        // nowhere to put it — `launch.environment` commits values, and
        // `secret_bindings` carries names precisely because secret values are
        // excluded from identity. Rather than invent a third place or pretend
        // the value does not matter, the subset refuses it.
        if let Some(name) = self
            .config
            .iter()
            .find(|(_, field)| field.kind != ConfigKindV1::Secret)
            .map(|(name, _)| name)
        {
            return Err(ManifestV1Error::Invalid {
                field: "config.<NAME>",
                reason: format!(
                    "{name} is a non-secret launch-supplied value: identity-bearing, but unknown \
                     when the contract is minted, and the contract has nowhere to put it. \
                     Author it as an [env] value, or declare it kind = \"secret\" so only the \
                     name is bound."
                ),
            });
        }

        let Some(web) = &self.web else {
            return Err(ManifestV1Error::Missing { field: "[web]" });
        };
        let _ = web;
        if self.seal_at.is_none() {
            return Err(ManifestV1Error::Missing {
                field: "[seal_at].command",
            });
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const MINIMAL: &str = r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python", "-m", "app"]

[web]
port = 8080
bind = "0.0.0.0"

[seal_at]
command = ["curl", "-fsS", "http://127.0.0.1:8080/health"]
"#;

    fn parse(text: &str) -> Result<CapsuleManifestV1, ManifestV1Error> {
        CapsuleManifestV1::from_toml(text)
    }

    #[test]
    fn the_minimal_step_four_manifest_parses_and_qualifies() {
        let manifest = parse(MINIMAL).expect("parses");
        assert_eq!(manifest.run.command, ["python", "-m", "app"]);
        assert_eq!(manifest.web.as_ref().unwrap().port, 8080);
        assert_eq!(manifest.web.as_ref().unwrap().bind, "0.0.0.0");
        manifest
            .validate_for_interactive_capture()
            .expect("qualifies for the Step-4 subset");
    }

    #[test]
    fn identity_matches_the_api_cross_language_golden_vector() {
        use sha2::{Digest as _, Sha256};

        use crate::capsule_lock::{
            CapsuleLock, LockManifestSection, LockSourceSelectionSection, compute_lock_id,
        };

        const CROSS_LANGUAGE_MANIFEST: &str = r#"
schema_version = "1"
name = "café-界"
version = "1.2.3"

[source]
root = "app"
ignore = ["dist/**", "é/**"]

[metadata]
short_description = "Unicode ✓"
tags = ["zeta", "日本語"]

[tools]
zeta = "2"
alpha = "1"

[[build.steps]]
command = ["npm", "run", "build"]

[run]
command = ["node", "server.js", "--message", "界"]

[env]
ZETA = "last"
ALPHA = "first"
"#;
        fn sha256_jcs<T: serde::Serialize>(value: &T) -> String {
            let bytes = serde_jcs::to_vec(value).expect("JCS");
            format!("sha256:{}", hex::encode(Sha256::digest(bytes)))
        }

        let manifest = CapsuleManifestV1::from_toml(CROSS_LANGUAGE_MANIFEST).expect("manifest");
        let normalized_manifest_digest = manifest.normalized_digest().expect("digest");
        let system_ignore = SYSTEM_SOURCE_IGNORE_V1
            .iter()
            .map(|value| (*value).to_string())
            .collect::<Vec<_>>();
        let mut effective_ignore = system_ignore.clone();
        effective_ignore.extend(manifest.source.ignore.clone());
        let source_selection = LockSourceSelectionSection {
            root: manifest.source.root.clone(),
            policy_version: SOURCE_FILTER_POLICY_VERSION_V1.to_string(),
            effective_ignore_digest: sha256_jcs(&effective_ignore),
            system_ignore_digest: sha256_jcs(&system_ignore),
            manifest_ignore_digest: sha256_jcs(&manifest.source.ignore),
            effective_ignore,
        };
        let source_closure_id = format!("sha256:{}", "1".repeat(64));
        let capsule_revision_id = format!(
            "caprev_{}",
            sha256_jcs(&serde_json::json!({
                "source_closure_id": source_closure_id,
                "normalized_manifest_digest": normalized_manifest_digest.clone(),
            }))
            .trim_start_matches("sha256:")
        );
        let lock = CapsuleLock {
            manifest: Some(LockManifestSection {
                schema_version: "1".to_string(),
                normalized_digest: normalized_manifest_digest.clone(),
            }),
            source_selection: Some(source_selection.clone()),
            ..CapsuleLock::default()
        };
        let lock_id = compute_lock_id(&lock).expect("lock id");

        assert_eq!(
            normalized_manifest_digest,
            "sha256:3aafdd92e46a4b185a63b1401e8b0fc2617f550b190d6f6f6a7da6f1df45be6b"
        );
        assert_eq!(
            source_selection.effective_ignore_digest,
            "sha256:b479692e904ce5b55ab62192a9d42db7451b2021da32c03739b0e6e6d8e82f23"
        );
        assert_eq!(
            capsule_revision_id,
            "caprev_5c96be2977a5e2d27d1bf01abddde011a609ad100bcd711468862d3c25298d12"
        );
        assert_eq!(
            lock_id.as_str(),
            "blake3:b93954b0ba65db20b880f72b118bf3a64f4b4172d132e612e283cfc76f1a2b19"
        );
    }

    /// The command is an argv, and argument boundaries survive verbatim —
    /// including an argument containing a space and an empty one.
    ///
    /// This is the difference v0.3 cannot express: it carries a single shell
    /// string, which has to be re-split by something, and whatever re-splits it
    /// is a second opinion about what the author meant.
    #[test]
    fn argument_boundaries_are_preserved_exactly() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python", "-m", "app", "--flag=a b", "", "--last"]

[web]
port = 8080
bind = "127.0.0.1"
"#,
        )
        .expect("parses");
        assert_eq!(
            manifest.run.command,
            ["python", "-m", "app", "--flag=a b", "", "--last"],
            "an argument with a space is ONE argument, and an empty argument is a real one"
        );
    }

    /// A shell is available by asking for one — and then it is visible in the
    /// identity as what it is, rather than implied.
    #[test]
    fn an_explicit_shell_is_allowed_and_stays_visible() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["sh", "-lc", "exec python -m app"]
"#,
        )
        .expect("parses");
        assert_eq!(manifest.run.command[0], "sh");
    }

    #[test]
    fn a_command_that_is_a_string_is_refused() {
        let error = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = "python -m app"
"#,
        )
        .expect_err("a shell string is not a v1 command");
        assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
    }

    #[test]
    fn an_empty_command_and_an_empty_program_are_refused() {
        for command in ["[]", r#"["", "app"]"#] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = {command}
"#
            ))
            .expect_err("must refuse {command}");
            assert!(
                matches!(
                    error,
                    ManifestV1Error::Invalid {
                        field: "run.command",
                        ..
                    }
                ),
                "{error}"
            );
        }
    }

    /// v0.3 does not become v1 by being read by this parser.
    #[test]
    fn a_v03_manifest_is_refused_by_the_v1_parser() {
        let error = parse(
            r#"
schema_version = "0.3"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]
"#,
        )
        .expect_err("0.3 is not v1");
        match error {
            ManifestV1Error::RequiresManifestV1 { found } => assert_eq!(found, "0.3"),
            other => panic!("expected RequiresManifestV1, got {other}"),
        }
    }

    /// The stable code the api and the wizard key on, raised at the entrance of
    /// a mint path rather than partway through an observation.
    #[test]
    fn the_mint_gate_names_what_it_found() {
        assert!(require_manifest_v1("1").is_ok());
        let error = require_manifest_v1("0.3").expect_err("refuses");
        assert!(
            error
                .to_string()
                .contains(EXECUTION_IDENTITY_REQUIRES_MANIFEST_V1),
            "{error}"
        );
        assert!(error.to_string().contains("\"0.3\""), "{error}");
    }

    /// A typo is an error, not a silently-ignored intent.
    #[test]
    fn an_unknown_field_is_refused_rather_than_ignored() {
        for extra in ["prot = 8080", "commnd = [\"x\"]"] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"
{extra}

[run]
command = ["python"]
"#
            ))
            .expect_err("unknown field");
            assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
        }
    }

    /// `bind` has no default. `0.0.0.0` is a fixture value throughout the tree,
    /// and ADR-015 §2 forbids promoting one to a normative default — an author
    /// who wants every interface says so.
    #[test]
    fn web_requires_an_explicit_bind() {
        let error = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[web]
port = 8080
"#,
        )
        .expect_err("bind has no default");
        assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
    }

    #[test]
    fn a_zero_port_is_refused() {
        let error = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[web]
port = 0
bind = "0.0.0.0"
"#,
        )
        .expect_err("port 0 is never a declared surface");
        assert!(
            matches!(
                error,
                ManifestV1Error::Invalid {
                    field: "web.port",
                    ..
                }
            ),
            "{error}"
        );
    }

    /// Every state field is authored — `access` in particular, which v0.3 has no
    /// counterpart for at all.
    #[test]
    fn state_declares_mount_access_schema_and_snapshot() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[state.data]
mount = "/data"
access = "read-write"
schema = "demo.data/v1"
snapshot = "exclude"
"#,
        )
        .expect("parses");
        let state = &manifest.state["data"];
        assert_eq!(state.mount, "/data");
        assert_eq!(state.access, StateAccessV1::ReadWrite);
        assert_eq!(state.schema, "demo.data/v1");
        assert_eq!(state.snapshot, SnapshotDispositionV1::Exclude);
    }

    #[test]
    fn a_state_block_missing_any_field_is_refused() {
        for missing in [
            r#"access = "read-write"
schema = "s"
snapshot = "exclude""#,
            r#"mount = "/data"
schema = "s"
snapshot = "exclude""#,
            r#"mount = "/data"
access = "read-write"
snapshot = "exclude""#,
            r#"mount = "/data"
access = "read-write"
schema = "s""#,
        ] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[state.data]
{missing}
"#
            ))
            .expect_err("every state field is required");
            assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
        }
    }

    #[test]
    fn a_relative_or_traversing_state_mount_is_refused() {
        for mount in ["data", "/data/../etc", "/data/"] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[state.data]
mount = "{mount}"
access = "read-only"
schema = "s"
snapshot = "exclude"
"#
            ))
            .expect_err("must refuse {mount}");
            assert!(
                matches!(
                    error,
                    ManifestV1Error::Invalid {
                        field: "state.<name>.mount",
                        ..
                    }
                ),
                "{mount}: {error}"
            );
        }
    }

    /// Outside the Step-4 subset is a REFUSAL BY NAME, not an approximation —
    /// and not a parse error either, because these are perfectly good capsules.
    #[test]
    fn features_outside_the_step_four_subset_are_refused_by_name() {
        let cases: [(&str, &str); 2] = [
            (
                r#"
[tools]
python = "3.12""#,
                "[tools]",
            ),
            (
                r#"
[state.data]
mount = "/data"
access = "read-write"
schema = "s"
snapshot = "exclude""#,
                "[state.<name>]",
            ),
        ];
        for (extra, feature) in cases {
            let manifest = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[web]
port = 8080
bind = "0.0.0.0"

[seal_at]
command = ["true"]
{extra}
"#
            ))
            .expect("it PARSES — it is a valid v1 manifest");
            let error = manifest
                .validate_for_interactive_capture()
                .expect_err("outside the subset");
            match error {
                ManifestV1Error::Unsupported { feature: named, .. } => {
                    assert_eq!(named, feature)
                }
                other => panic!("expected Unsupported({feature}), got {other}"),
            }
        }
    }

    #[test]
    fn static_web_output_places_build_steps_in_the_interactive_subset() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "static-demo"
version = "0.1.0"

[[build.steps]]
command = ["sh", "-c", "mkdir -p dist && cp index.html dist/"]

[run]
command = ["python3", "-m", "http.server", "8000"]

[web]
port = 8000
bind = "0.0.0.0"

[seal_at]
command = ["true"]

[outputs.static_web]
root = "dist"
entry_path = "index.html"
"#,
        )
        .expect("valid static web manifest");

        manifest
            .validate_for_interactive_capture()
            .expect("the declared static output places the build result");
    }

    /// A variable is a VALUE or a NAME, never both.
    ///
    /// The Execution Contract refuses the same contradiction at generation time
    /// (`EnvironmentNameIsSecretBinding`); refusing it here as well costs
    /// nothing and tells the author which line to change.
    #[test]
    fn a_variable_cannot_be_both_an_authored_value_and_a_config_field() {
        let error = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[env]
DATABASE_URL = "postgres://localhost/db"

[config.DATABASE_URL]
kind = "secret"
required = true
"#,
        )
        .expect_err("a variable is a value or a name, never both");
        match error {
            ManifestV1Error::Invalid { field, reason } => {
                assert_eq!(field, "config.<NAME>");
                assert!(reason.contains("never both"), "{reason}");
            }
            other => panic!("{other}"),
        }
    }

    /// A secret-bearing NAME authored as a plain value is refused where the
    /// author can see it, rather than at the identity gate much later.
    ///
    /// The heuristic is defence in depth, not the boundary — `secret_bindings`
    /// is authoritative — but a name it does catch should be caught at the line
    /// that wrote it.
    #[test]
    fn a_secret_bearing_name_cannot_be_an_authored_env_value() {
        for name in ["API_TOKEN", "app_secret", "DB_PASSWORD", "MY_API_KEY"] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[env]
{name} = "hunter2"
"#
            ))
            .expect_err("must refuse {name}");
            match error {
                ManifestV1Error::Invalid { field, reason } => {
                    assert_eq!(field, "env.<NAME>");
                    assert!(reason.contains("kind = \"secret\""), "{reason}");
                }
                other => panic!("{name}: {other}"),
            }
        }
    }

    /// Both `kind` and `required` are explicit. v0.3 has no `required` at all
    /// and defaults its kind to `secret`; neither default is inherited.
    #[test]
    fn a_config_field_must_state_both_kind_and_required() {
        for partial in [r#"kind = "secret""#, "required = true"] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[config.API_KEY]
{partial}
"#
            ))
            .expect_err("both are explicit");
            assert!(
                matches!(error, ManifestV1Error::Toml(_)),
                "{partial}: {error}"
            );
        }
    }

    #[test]
    fn a_secret_config_field_and_an_authored_value_coexist_when_they_are_different_names() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[env]
NODE_ENV = "production"

[config.API_KEY]
kind = "secret"
required = true
"#,
        )
        .expect("parses");
        assert_eq!(manifest.env["NODE_ENV"], "production");
        assert_eq!(manifest.config["API_KEY"].kind, ConfigKindV1::Secret);
        assert!(manifest.config["API_KEY"].required);
    }

    /// A non-secret launch-supplied value is identity-bearing and unknown when
    /// the contract is minted — the contract has nowhere to put it, so the
    /// subset says so instead of inventing a place.
    #[test]
    fn a_non_secret_launch_supplied_value_is_refused_by_the_subset() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[web]
port = 8080
bind = "0.0.0.0"

[seal_at]
command = ["true"]

[config.REGION]
kind = "string"
required = true
"#,
        )
        .expect("it PARSES — it is a valid v1 manifest");
        let error = manifest
            .validate_for_interactive_capture()
            .expect_err("outside the subset");
        match error {
            ManifestV1Error::Invalid { field, reason } => {
                assert_eq!(field, "config.<NAME>");
                assert!(reason.contains("nowhere to put it"), "{reason}");
            }
            other => panic!("{other}"),
        }
    }

    #[test]
    fn a_non_posix_variable_name_is_refused() {
        for (table, line) in [
            ("env", "1BAD = \"x\""),
            ("config.1BAD", "kind = \"secret\"\nrequired = true"),
        ] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[{table}]
{line}
"#
            ))
            .expect_err("must refuse a non-POSIX name");
            assert!(
                matches!(error, ManifestV1Error::Invalid { .. }),
                "{table}: {error}"
            );
        }
    }

    /// Step 4 cannot accept a candidate without an acceptance program, and
    /// cannot make a preview reachable without a surface.
    #[test]
    fn the_step_four_subset_requires_web_and_seal_at() {
        let without_seal = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[web]
port = 8080
bind = "0.0.0.0"
"#,
        )
        .expect("parses");
        assert!(matches!(
            without_seal.validate_for_interactive_capture(),
            Err(ManifestV1Error::Missing {
                field: "[seal_at].command"
            })
        ));

        let without_web = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[seal_at]
command = ["true"]
"#,
        )
        .expect("parses");
        assert!(matches!(
            without_web.validate_for_interactive_capture(),
            Err(ManifestV1Error::Missing { field: "[web]" })
        ));
    }

    #[test]
    fn a_seal_at_timeout_outside_the_policy_ceiling_is_refused() {
        for seconds in [0, MAX_SEAL_AT_TIMEOUT_SECONDS + 1] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

[seal_at]
command = ["true"]
timeout_seconds = {seconds}
"#
            ))
            .expect_err("outside the ceiling");
            assert!(
                matches!(
                    error,
                    ManifestV1Error::Invalid {
                        field: "seal_at.timeout_seconds",
                        ..
                    }
                ),
                "{seconds}: {error}"
            );
        }
    }

    /// A v1 manifest round-trips through its own serializer without acquiring
    /// or losing a field — the property that keeps a written manifest readable
    /// by the same parser.
    #[test]
    fn a_manifest_round_trips() {
        let manifest = parse(MINIMAL).expect("parses");
        let text = toml::to_string(&manifest).expect("serialize");
        assert_eq!(
            CapsuleManifestV1::from_toml(&text).expect("reparse"),
            manifest
        );
    }

    #[test]
    fn unified_source_and_metadata_are_strict_and_identity_bearing() {
        let base = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[source]
root = "."
ignore = ["dist/**", "!dist/store-card.png"]

[metadata]
short_description = "First description"
tags = ["developer-tool"]

[metadata.store]
category = "developer_tools"
subcategory = "utilities"

[metadata.assets.icon]
path = "assets/icon.png"

[metadata.assets.banner]
url = "https://assets.example/banner.webp"
content_digest = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
artifact_ref = "ato-asset://sha256/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
media_type = "image/webp"
origin_url = "https://origin.example/banner.webp"

[run]
command = ["python"]
"#,
        )
        .expect("unified manifest parses");
        let mut changed = base.clone();
        changed.metadata.short_description = Some("Second description".to_string());
        assert_ne!(
            base.normalized_digest().expect("base digest"),
            changed.normalized_digest().expect("metadata digest"),
            "Store metadata is part of the normalized manifest identity"
        );
        assert!(
            base.source_path_is_included("dist/store-card.png", false)
                .unwrap()
        );
        assert!(!base.source_path_is_included("dist/app.js", false).unwrap());
    }

    #[test]
    fn safety_ignore_cannot_be_reincluded() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[source]
ignore = ["!.env", "!keys/id_rsa"]

[run]
command = ["python"]
"#,
        )
        .expect("patterns are valid author intent");
        assert!(!manifest.source_path_is_included(".env", false).unwrap());
        assert!(
            !manifest
                .source_path_is_included("keys/id_rsa", false)
                .unwrap()
        );
    }

    #[test]
    fn ignored_or_traversing_asset_paths_are_refused() {
        for asset in ["../icon.png", "dist/icon.png"] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[source]
ignore = ["dist/**"]

[metadata.assets.icon]
path = "{asset}"

[run]
command = ["python"]
"#
            ))
            .expect_err("unsafe asset path");
            assert!(
                matches!(
                    error,
                    ManifestV1Error::Invalid {
                        field: "metadata.assets.icon",
                        ..
                    }
                ),
                "{asset}: {error}"
            );
        }
    }

    #[test]
    fn an_asset_locator_requires_exactly_one_known_locator() {
        for locator in [
            r#"path = "assets/icon.png"
url = "https://assets.example/icon.png""#,
            r#"digest = "sha256:abc""#,
        ] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[metadata.assets.icon]
{locator}

[run]
command = ["python"]
"#
            ))
            .expect_err("ambiguous or unknown asset locator");
            assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
        }
    }

    #[test]
    fn source_and_metadata_unknown_fields_are_refused() {
        for extra in [
            "[source]\nroot = \".\"\ninclude = [\"src/**\"]",
            "[metadata]\nshort_description = \"demo\"\nfeatured = true",
        ] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

{extra}

[run]
command = ["python"]
"#
            ))
            .expect_err("unknown unified manifest field");
            assert!(matches!(error, ManifestV1Error::Toml(_)), "{error}");
        }
    }

    #[test]
    fn static_web_output_declares_the_lane_without_enabling_it_by_dist() {
        let manifest = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["npm", "run", "preview"]

[outputs.static_web]
root = "dist"
entry_path = "index.html"
spa_fallback = true
connect_src = ["https://api.example.com", "wss://push.example.com"]
"#,
        )
        .expect("explicit static web output parses");
        let outputs = manifest.outputs.expect("outputs declared");
        let static_web = outputs.static_web.expect("static web lane declared");
        assert_eq!(static_web.root, "dist");
        assert_eq!(static_web.entry_path, "index.html");
        assert!(static_web.spa_fallback);
        assert_eq!(
            static_web.connect_src,
            ["https://api.example.com", "wss://push.example.com"]
        );

        // Absent `[outputs.static_web]` keeps the snapshot-only default. The
        // normalized digest must not change for an unmodified manifest.
        let without = parse(
            r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["npm", "run", "preview"]
"#,
        )
        .expect("snapshot-only manifest parses");
        assert!(without.outputs.is_none());
    }

    #[test]
    fn static_web_output_rejects_unsafe_or_unordered_contracts() {
        for (toml, fragment) in [
            (
                r#"[outputs.static_web]
root = "/absolute/dist"
entry_path = "index.html""#,
                "outputs.static_web.root",
            ),
            (
                r#"[outputs.static_web]
root = "../dist"
entry_path = "index.html""#,
                "outputs.static_web.root",
            ),
            (
                r#"[outputs.static_web]
root = "dist%2fescaped"
entry_path = "index.html""#,
                "outputs.static_web.root",
            ),
            (
                r#"[outputs.static_web]
root = "dist"
entry_path = "index%2f.html""#,
                "outputs.static_web.entry_path",
            ),
            (
                r#"[outputs.static_web]
root = "dist"
entry_path = "assets\\app.js""#,
                "outputs.static_web.entry_path",
            ),
            (
                r#"[outputs.static_web]
root = "dist"
entry_path = "assets/../app.js""#,
                "outputs.static_web.entry_path",
            ),
            (
                r#"[outputs.static_web]
root = "dist"
entry_path = "index.html"
connect_src = ["https://api.example.com", "http://insecure.example.com"]"#,
                "outputs.static_web.connect_src[]",
            ),
            (
                r#"[outputs.static_web]
root = "dist"
entry_path = "index.html"
connect_src = ["wss://push.example.com", "https://api.example.com"]"#,
                "outputs.static_web.connect_src[]",
            ),
            (
                r#"[outputs.static_web]
root = "dist"
entry_path = "index.html"
connect_src = ["https://api.example.com", "https://api.example.com"]"#,
                "outputs.static_web.connect_src[]",
            ),
        ] {
            let error = parse(&format!(
                r#"
schema_version = "1"
name = "demo"
version = "0.1.0"

[run]
command = ["python"]

{toml}
"#
            ))
            .expect_err("must refuse the invalid static web contract");
            match error {
                ManifestV1Error::Invalid { field, .. } => assert_eq!(field, fragment),
                other => panic!("{other}"),
            }
        }
    }
}
