use anyhow::Result;
use std::fs;
use std::path::Path;

use super::detect::{DetectedNode, DetectedProject, NodePackageManager, ProjectType};

#[derive(Debug, Clone)]
pub struct ProjectInfo {
    pub name: String,
    pub project_type: ProjectType,
    pub entrypoint: Vec<String>,
    pub node_dev_entrypoint: Option<Vec<String>>,
    #[allow(dead_code)]
    pub node_release_entrypoint: Option<Vec<String>>,
}

pub struct ManifestMeta<'a> {
    pub generated_by: &'a str,
    pub description: &'a str,
}

pub fn generate_manifest(info: &ProjectInfo, meta: ManifestMeta<'_>) -> String {
    let mut entrypoint = if info.entrypoint.is_empty() {
        "echo".to_string()
    } else {
        info.entrypoint[0].clone()
    };
    let mut cmd = if info.entrypoint.len() > 1 {
        info.entrypoint[1..].to_vec()
    } else {
        Vec::new()
    };

    if info.entrypoint.is_empty() {
        cmd.push("Hello, capsule!".to_string());
    }

    // Prefer direct script path for common Python patterns (python main.py).
    // Keep interpreter form when flags/modules are used (python -m app, python -c ...).
    if matches!(info.project_type, ProjectType::Python)
        && info.entrypoint.len() >= 2
        && info.entrypoint[0]
            .to_ascii_lowercase()
            .starts_with("python")
        && !info.entrypoint[1].starts_with('-')
    {
        entrypoint = info.entrypoint[1].clone();
        cmd = if info.entrypoint.len() > 2 {
            info.entrypoint[2..].to_vec()
        } else {
            Vec::new()
        };
    }

    let cmd_line = if cmd.is_empty() {
        String::new()
    } else {
        format!("cmd = [{}]", render_toml_string_array(&cmd))
    };

    // Emit a `driver` field so that the auto-provisioning diagnostics
    // (`detect_missing_lockfile`, `detect_runtime_selection_required`) can
    // identify the runtime required for this project.  Without `driver`,
    // `plan.execution_driver()` returns `None` and both detect functions
    // short-circuit, which means no provisioning issues are ever collected,
    // the shadow-workspace phase is skipped entirely, and
    // `RuntimeManager::for_plan` fails with E999 (missing capsule.lock.json)
    // on every first run of a local directory.
    let driver_line = match info.project_type {
        ProjectType::Python => "driver = \"python\"\n".to_string(),
        ProjectType::NodeJs => {
            // Use the first element of the *original* entrypoint vec (before any
            // Python-style rewriting above) to distinguish the JS runtime family.
            let first = info
                .entrypoint
                .first()
                .map(|s| s.to_ascii_lowercase())
                .unwrap_or_default();
            match first.as_str() {
                "node" | "npm" | "yarn" | "pnpm" | "npx" => "driver = \"node\"\n".to_string(),
                "deno" => "driver = \"deno\"\n".to_string(),
                "bun" => "driver = \"bun\"\n".to_string(),
                _ => String::new(),
            }
        }
        // Rust, Go, Ruby, Unknown — native binaries; no managed runtime needed.
        _ => String::new(),
    };

    format!(
        r#"# Capsule Manifest - Multi-Target Native v0.2
# Generated by: {generated_by}

schema_version = "0.3"
name = "{name}"
version = "0.1.0"
type = "app"

runtime = "source"
{driver_line}entrypoint = "{entrypoint}"
{cmd_line}
[metadata]
description = "{description}"

[requirements]

[storage]

[routing]
"#,
        generated_by = meta.generated_by,
        name = toml_escape_string(&info.name),
        description = toml_escape_string(meta.description),
        entrypoint = toml_escape_string(&entrypoint),
        cmd_line = cmd_line,
        driver_line = driver_line,
    )
}

pub fn generate_manual_manifest_stub(name: &str) -> String {
    format!(
        r#"# Capsule Manifest - Manual Starter
# Edit this file before rerunning `ato run`.

schema_version = "0.3"
name = "{name}"
version = "0.1.0"
type = "app"

runtime = "source"
cmd = ["Edit capsule.toml before rerunning ato run"]
run = "echo"
[metadata]
description = "Manual starter manifest. Edit [targets.cli] before running."

[requirements]

[storage]

[routing]
"#,
        name = toml_escape_string(name),
    )
}

pub fn project_info_from_detection(detected: &DetectedProject) -> Result<ProjectInfo> {
    let name = detected.name.clone();

    match detected.project_type {
        ProjectType::Python => Ok(ProjectInfo {
            name,
            project_type: ProjectType::Python,
            entrypoint: detect_python_entrypoint(&detected.dir),
            node_dev_entrypoint: None,
            node_release_entrypoint: None,
        }),

        ProjectType::NodeJs => {
            let node = detected
                .node
                .as_ref()
                .expect("node detection must exist for NodeJs project");

            let dev = node_dev_entrypoint(node);
            let release = node_release_entrypoint(&detected.dir, node);

            Ok(ProjectInfo {
                name,
                project_type: ProjectType::NodeJs,
                entrypoint: release.clone(),
                node_dev_entrypoint: dev,
                node_release_entrypoint: Some(release),
            })
        }

        ProjectType::Rust => {
            let bin = detect_rust_binary_name(&detected.dir, &name);
            Ok(ProjectInfo {
                name,
                project_type: ProjectType::Rust,
                entrypoint: vec![normalize_relative_executable(&bin)],
                node_dev_entrypoint: Some(vec!["cargo".to_string(), "run".to_string()]),
                node_release_entrypoint: Some(vec![normalize_relative_executable(&bin)]),
            })
        }

        ProjectType::Go => {
            let bin = normalize_relative_executable(&name);
            Ok(ProjectInfo {
                name,
                project_type: ProjectType::Go,
                entrypoint: vec![bin.clone()],
                node_dev_entrypoint: Some(vec![
                    "go".to_string(),
                    "run".to_string(),
                    ".".to_string(),
                ]),
                node_release_entrypoint: Some(vec![bin]),
            })
        }

        ProjectType::Ruby => Ok(ProjectInfo {
            name,
            project_type: ProjectType::Ruby,
            entrypoint: detect_ruby_entrypoint(&detected.dir),
            node_dev_entrypoint: None,
            node_release_entrypoint: None,
        }),

        ProjectType::Unknown => Ok(ProjectInfo {
            name,
            project_type: ProjectType::Unknown,
            entrypoint: detect_generic_entrypoint(&detected.dir),
            node_dev_entrypoint: None,
            node_release_entrypoint: None,
        }),
    }
}

fn node_dev_entrypoint(node: &DetectedNode) -> Option<Vec<String>> {
    if !node.scripts.has_dev {
        return None;
    }

    match node.package_manager {
        NodePackageManager::Bun => Some(vec![
            "bun".to_string(),
            "run".to_string(),
            "dev".to_string(),
        ]),
        NodePackageManager::Deno => Some(vec![
            "deno".to_string(),
            "task".to_string(),
            "dev".to_string(),
        ]),
        NodePackageManager::Pnpm => Some(vec!["pnpm".to_string(), "dev".to_string()]),
        NodePackageManager::Yarn => Some(vec!["yarn".to_string(), "dev".to_string()]),
        NodePackageManager::Npm | NodePackageManager::Unknown => Some(vec![
            "npm".to_string(),
            "run".to_string(),
            "dev".to_string(),
        ]),
    }
}

fn node_release_entrypoint(dir: &Path, node: &DetectedNode) -> Vec<String> {
    if node.scripts.has_start {
        return match node.package_manager {
            NodePackageManager::Bun => {
                vec!["bun".to_string(), "run".to_string(), "start".to_string()]
            }
            NodePackageManager::Deno => {
                vec!["deno".to_string(), "task".to_string(), "start".to_string()]
            }
            NodePackageManager::Pnpm => vec!["pnpm".to_string(), "start".to_string()],
            NodePackageManager::Yarn => vec!["yarn".to_string(), "start".to_string()],
            NodePackageManager::Npm | NodePackageManager::Unknown => {
                vec!["npm".to_string(), "start".to_string()]
            }
        };
    }

    // If a common dist artifact exists (especially for Bun/Hono setups), prefer running it.
    if dir.join("dist/server.js").exists() {
        if node.is_bun {
            return vec!["bun".to_string(), "dist/server.js".to_string()];
        }
        if matches!(node.package_manager, NodePackageManager::Deno) {
            return vec!["dist/server.js".to_string()];
        }
        return vec!["node".to_string(), "dist/server.js".to_string()];
    }

    // Only use `node.main` as a direct entrypoint when it is a file that
    // bare Node.js can execute AND actually exists in the source tree.
    // `main = "index.html"`, `main = "package.json"`, or pointing at a built
    // artifact that isn't in the source checkout are all filtered out here.
    if let Some(main) = node
        .main
        .as_ref()
        .filter(|m| is_directly_runnable_node_main(m))
        .filter(|m| dir.join(m).exists())
    {
        if node.is_bun {
            return vec!["bun".to_string(), main.clone()];
        }
        if matches!(node.package_manager, NodePackageManager::Deno) {
            return vec![main.clone()];
        }
        return vec!["node".to_string(), main.clone()];
    }

    // Fallbacks based on typical file layout.
    let candidates: &[&str] = if matches!(node.package_manager, NodePackageManager::Deno) {
        &[
            "src/main.tsx",
            "src/main.ts",
            "src/main.jsx",
            "src/main.js",
            "src/mod.ts",
            "src/index.ts",
            "src/index.jsx",
            "src/index.js",
            "main.tsx",
            "main.ts",
            "main.jsx",
            "main.js",
            "mod.ts",
            "index.ts",
            "index.jsx",
            "index.js",
        ]
    } else if node.is_bun {
        &[
            "src/index.ts",
            "src/main.ts",
            "index.ts",
            "main.ts",
            "index.js",
            "main.js",
            "app.js",
            "server.js",
        ]
    } else {
        &["index.js", "main.js", "app.js", "server.js"]
    };

    for candidate in candidates {
        if dir.join(candidate).exists() {
            if node.is_bun {
                return vec!["bun".to_string(), candidate.to_string()];
            }
            if matches!(node.package_manager, NodePackageManager::Deno) {
                return vec![candidate.to_string()];
            }
            return vec!["node".to_string(), candidate.to_string()];
        }
    }

    if matches!(node.package_manager, NodePackageManager::Deno) {
        vec!["main.ts".to_string()]
    } else {
        vec!["npm".to_string(), "start".to_string()]
    }
}

/// Returns true for paths that bare Node.js can execute directly.
/// Extensionless paths (e.g. `dist/server`, `./bin/www`) are allowed;
/// TypeScript, JSX, HTML, JSON etc. are not.
fn is_directly_runnable_node_main(path: &str) -> bool {
    let ext = std::path::Path::new(path)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("");
    ext.is_empty() || matches!(ext, "js" | "mjs" | "cjs")
}

fn detect_python_entrypoint(dir: &Path) -> Vec<String> {
    for candidate in ["main.py", "app.py", "run.py", "server.py"] {
        if dir.join(candidate).exists() {
            return vec!["python".to_string(), candidate.to_string()];
        }
    }

    if dir.join("__main__.py").exists() {
        return vec!["python".to_string(), ".".to_string()];
    }

    if dir.join("pyproject.toml").exists() {
        return vec!["python".to_string(), "-m".to_string(), "app".to_string()];
    }

    vec!["python".to_string(), "main.py".to_string()]
}

fn detect_ruby_entrypoint(dir: &Path) -> Vec<String> {
    if dir.join("config.ru").exists() {
        return vec![
            "bundle".to_string(),
            "exec".to_string(),
            "rackup".to_string(),
        ];
    }

    for candidate in ["app.rb", "main.rb", "server.rb"] {
        if dir.join(candidate).exists() {
            return vec!["ruby".to_string(), candidate.to_string()];
        }
    }

    vec!["ruby".to_string(), "app.rb".to_string()]
}

fn detect_generic_entrypoint(dir: &Path) -> Vec<String> {
    for (file, cmd) in [
        ("main.py", vec!["python", "main.py"]),
        ("index.js", vec!["node", "index.js"]),
        ("main.sh", vec!["bash", "main.sh"]),
        ("run.sh", vec!["bash", "run.sh"]),
    ] {
        if dir.join(file).exists() {
            return cmd.iter().map(|s| s.to_string()).collect();
        }
    }

    if dir.join("Dockerfile").exists() {
        return vec![
            "echo".to_string(),
            "Container project - specify entrypoint".to_string(),
        ];
    }

    vec![]
}

fn normalize_relative_executable(name: &str) -> String {
    let trimmed = name.trim();
    if trimmed.is_empty() {
        return "./app".to_string();
    }
    if trimmed.starts_with("./") || trimmed.contains('/') {
        return trimmed.to_string();
    }
    format!("./{}", trimmed)
}

fn detect_rust_binary_name(dir: &Path, fallback: &str) -> String {
    let cargo_toml = dir.join("Cargo.toml");
    let Ok(content) = fs::read_to_string(&cargo_toml) else {
        return fallback.to_string();
    };
    let Ok(value) = toml::from_str::<toml::Value>(&content) else {
        return fallback.to_string();
    };

    // Prefer first [[bin]] name when specified.
    if let Some(bin0) = value
        .get("bin")
        .and_then(|b| b.as_array())
        .and_then(|a| a.first())
    {
        if let Some(name) = bin0
            .get("name")
            .and_then(|n| n.as_str())
            .map(|s| s.trim())
            .filter(|s| !s.is_empty())
        {
            return name.to_string();
        }
    }

    // Otherwise use [package].name.
    if let Some(name) = value
        .get("package")
        .and_then(|p| p.get("name"))
        .and_then(|n| n.as_str())
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
    {
        return name.to_string();
    }

    fallback.to_string()
}

fn toml_escape_string(input: &str) -> String {
    input
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn render_toml_string_array(values: &[String]) -> String {
    values
        .iter()
        .map(|v| format!("\"{}\"", toml_escape_string(v)))
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_directly_runnable_node_main_accepts_js_extensions() {
        assert!(is_directly_runnable_node_main("index.js"));
        assert!(is_directly_runnable_node_main("dist/server.mjs"));
        assert!(is_directly_runnable_node_main("lib/app.cjs"));
    }

    #[test]
    fn is_directly_runnable_node_main_accepts_extensionless_paths() {
        assert!(is_directly_runnable_node_main("dist/server"));
        assert!(is_directly_runnable_node_main("bin/www"));
    }

    #[test]
    fn is_directly_runnable_node_main_rejects_non_js_extensions() {
        assert!(!is_directly_runnable_node_main("index.html"));
        assert!(!is_directly_runnable_node_main("package.json"));
        assert!(!is_directly_runnable_node_main("src/main.tsx"));
        assert!(!is_directly_runnable_node_main("src/server.ts"));
        assert!(!is_directly_runnable_node_main("app.jsx"));
    }
}
