// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartRequest {
    #[prost(string, tag = "1")]
    pub control_url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub auth_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub socks_port: u32,
    /// Allowed egress destinations (domains/CIDR)
    #[prost(string, repeated, tag = "5")]
    pub allow_net: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartResponse {
    #[prost(enumeration = "TsnetState", tag = "1")]
    pub state: i32,
    #[prost(uint32, tag = "2")]
    pub socks_port: u32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StopRequest {
    #[prost(bool, tag = "1")]
    pub force: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopResponse {
    #[prost(enumeration = "TsnetState", tag = "1")]
    pub state: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatusRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    #[prost(enumeration = "TsnetState", tag = "1")]
    pub state: i32,
    #[prost(uint32, tag = "2")]
    pub socks_port: u32,
    #[prost(bool, tag = "3")]
    pub connected: bool,
    #[prost(string, tag = "4")]
    pub last_error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServeRequest {
    /// local address to forward, e.g. 127.0.0.1:3000
    #[prost(string, tag = "1")]
    pub target_addr: ::prost::alloc::string::String,
    /// tailnet port to listen (0 = auto)
    #[prost(uint32, tag = "2")]
    pub listen_port: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServeResponse {
    #[prost(bool, tag = "1")]
    pub running: bool,
    #[prost(uint32, tag = "2")]
    pub listen_port: u32,
    #[prost(string, tag = "3")]
    pub listen_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServeStopRequest {
    #[prost(bool, tag = "1")]
    pub force: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServeStopResponse {
    #[prost(bool, tag = "1")]
    pub running: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServeStatusRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServeStatusResponse {
    #[prost(bool, tag = "1")]
    pub running: bool,
    #[prost(uint32, tag = "2")]
    pub listen_port: u32,
    #[prost(string, tag = "3")]
    pub listen_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub last_error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TsnetState {
    Unspecified = 0,
    Stopped = 1,
    Starting = 2,
    Running = 3,
    Stopping = 4,
    Failed = 5,
}
impl TsnetState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TSNET_STATE_UNSPECIFIED",
            Self::Stopped => "TSNET_STATE_STOPPED",
            Self::Starting => "TSNET_STATE_STARTING",
            Self::Running => "TSNET_STATE_RUNNING",
            Self::Stopping => "TSNET_STATE_STOPPING",
            Self::Failed => "TSNET_STATE_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TSNET_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "TSNET_STATE_STOPPED" => Some(Self::Stopped),
            "TSNET_STATE_STARTING" => Some(Self::Starting),
            "TSNET_STATE_RUNNING" => Some(Self::Running),
            "TSNET_STATE_STOPPING" => Some(Self::Stopping),
            "TSNET_STATE_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod tsnet_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct TsnetServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TsnetServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TsnetServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TsnetServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TsnetServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn start(
            &mut self,
            request: impl tonic::IntoRequest<super::StartRequest>,
        ) -> std::result::Result<tonic::Response<super::StartResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tsnet.v1.TsnetService/Start",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tsnet.v1.TsnetService", "Start"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stop(
            &mut self,
            request: impl tonic::IntoRequest<super::StopRequest>,
        ) -> std::result::Result<tonic::Response<super::StopResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tsnet.v1.TsnetService/Stop",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tsnet.v1.TsnetService", "Stop"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn status(
            &mut self,
            request: impl tonic::IntoRequest<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tsnet.v1.TsnetService/Status",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tsnet.v1.TsnetService", "Status"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn start_serve(
            &mut self,
            request: impl tonic::IntoRequest<super::ServeRequest>,
        ) -> std::result::Result<tonic::Response<super::ServeResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tsnet.v1.TsnetService/StartServe",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tsnet.v1.TsnetService", "StartServe"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stop_serve(
            &mut self,
            request: impl tonic::IntoRequest<super::ServeStopRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ServeStopResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tsnet.v1.TsnetService/StopServe",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tsnet.v1.TsnetService", "StopServe"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn serve_status(
            &mut self,
            request: impl tonic::IntoRequest<super::ServeStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ServeStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tsnet.v1.TsnetService/ServeStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tsnet.v1.TsnetService", "ServeStatus"));
            self.inner.unary(req, path, codec).await
        }
    }
}
