// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: tsnet.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TsnetState int32

const (
	TsnetState_TSNET_STATE_UNSPECIFIED TsnetState = 0
	TsnetState_TSNET_STATE_STOPPED     TsnetState = 1
	TsnetState_TSNET_STATE_STARTING    TsnetState = 2
	TsnetState_TSNET_STATE_RUNNING     TsnetState = 3
	TsnetState_TSNET_STATE_STOPPING    TsnetState = 4
	TsnetState_TSNET_STATE_FAILED      TsnetState = 5
)

// Enum value maps for TsnetState.
var (
	TsnetState_name = map[int32]string{
		0: "TSNET_STATE_UNSPECIFIED",
		1: "TSNET_STATE_STOPPED",
		2: "TSNET_STATE_STARTING",
		3: "TSNET_STATE_RUNNING",
		4: "TSNET_STATE_STOPPING",
		5: "TSNET_STATE_FAILED",
	}
	TsnetState_value = map[string]int32{
		"TSNET_STATE_UNSPECIFIED": 0,
		"TSNET_STATE_STOPPED":     1,
		"TSNET_STATE_STARTING":    2,
		"TSNET_STATE_RUNNING":     3,
		"TSNET_STATE_STOPPING":    4,
		"TSNET_STATE_FAILED":      5,
	}
)

func (x TsnetState) Enum() *TsnetState {
	p := new(TsnetState)
	*p = x
	return p
}

func (x TsnetState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TsnetState) Descriptor() protoreflect.EnumDescriptor {
	return file_tsnet_proto_enumTypes[0].Descriptor()
}

func (TsnetState) Type() protoreflect.EnumType {
	return &file_tsnet_proto_enumTypes[0]
}

func (x TsnetState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TsnetState.Descriptor instead.
func (TsnetState) EnumDescriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{0}
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlUrl    string                 `protobuf:"bytes,1,opt,name=control_url,json=controlUrl,proto3" json:"control_url,omitempty"`
	AuthKey       string                 `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	SocksPort     uint32                 `protobuf:"varint,4,opt,name=socks_port,json=socksPort,proto3" json:"socks_port,omitempty"`
	AllowNet      []string               `protobuf:"bytes,5,rep,name=allow_net,json=allowNet,proto3" json:"allow_net,omitempty"` // Allowed egress destinations (domains/CIDR)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_tsnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetControlUrl() string {
	if x != nil {
		return x.ControlUrl
	}
	return ""
}

func (x *StartRequest) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *StartRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *StartRequest) GetSocksPort() uint32 {
	if x != nil {
		return x.SocksPort
	}
	return 0
}

func (x *StartRequest) GetAllowNet() []string {
	if x != nil {
		return x.AllowNet
	}
	return nil
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TsnetState             `protobuf:"varint,1,opt,name=state,proto3,enum=tsnet.v1.TsnetState" json:"state,omitempty"`
	SocksPort     uint32                 `protobuf:"varint,2,opt,name=socks_port,json=socksPort,proto3" json:"socks_port,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_tsnet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetState() TsnetState {
	if x != nil {
		return x.State
	}
	return TsnetState_TSNET_STATE_UNSPECIFIED
}

func (x *StartResponse) GetSocksPort() uint32 {
	if x != nil {
		return x.SocksPort
	}
	return 0
}

func (x *StartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_tsnet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TsnetState             `protobuf:"varint,1,opt,name=state,proto3,enum=tsnet.v1.TsnetState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_tsnet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetState() TsnetState {
	if x != nil {
		return x.State
	}
	return TsnetState_TSNET_STATE_UNSPECIFIED
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_tsnet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TsnetState             `protobuf:"varint,1,opt,name=state,proto3,enum=tsnet.v1.TsnetState" json:"state,omitempty"`
	SocksPort     uint32                 `protobuf:"varint,2,opt,name=socks_port,json=socksPort,proto3" json:"socks_port,omitempty"`
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_tsnet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetState() TsnetState {
	if x != nil {
		return x.State
	}
	return TsnetState_TSNET_STATE_UNSPECIFIED
}

func (x *StatusResponse) GetSocksPort() uint32 {
	if x != nil {
		return x.SocksPort
	}
	return 0
}

func (x *StatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *StatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ServeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetAddr    string                 `protobuf:"bytes,1,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"`  // local address to forward, e.g. 127.0.0.1:3000
	ListenPort    uint32                 `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"` // tailnet port to listen (0 = auto)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeRequest) Reset() {
	*x = ServeRequest{}
	mi := &file_tsnet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeRequest) ProtoMessage() {}

func (x *ServeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeRequest.ProtoReflect.Descriptor instead.
func (*ServeRequest) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{6}
}

func (x *ServeRequest) GetTargetAddr() string {
	if x != nil {
		return x.TargetAddr
	}
	return ""
}

func (x *ServeRequest) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

type ServeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	ListenPort    uint32                 `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeResponse) Reset() {
	*x = ServeResponse{}
	mi := &file_tsnet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeResponse) ProtoMessage() {}

func (x *ServeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeResponse.ProtoReflect.Descriptor instead.
func (*ServeResponse) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{7}
}

func (x *ServeResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ServeResponse) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *ServeResponse) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *ServeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServeStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeStopRequest) Reset() {
	*x = ServeStopRequest{}
	mi := &file_tsnet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeStopRequest) ProtoMessage() {}

func (x *ServeStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeStopRequest.ProtoReflect.Descriptor instead.
func (*ServeStopRequest) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{8}
}

func (x *ServeStopRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ServeStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeStopResponse) Reset() {
	*x = ServeStopResponse{}
	mi := &file_tsnet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeStopResponse) ProtoMessage() {}

func (x *ServeStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeStopResponse.ProtoReflect.Descriptor instead.
func (*ServeStopResponse) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{9}
}

func (x *ServeStopResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ServeStopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeStatusRequest) Reset() {
	*x = ServeStatusRequest{}
	mi := &file_tsnet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeStatusRequest) ProtoMessage() {}

func (x *ServeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeStatusRequest.ProtoReflect.Descriptor instead.
func (*ServeStatusRequest) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{10}
}

type ServeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	ListenPort    uint32                 `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeStatusResponse) Reset() {
	*x = ServeStatusResponse{}
	mi := &file_tsnet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeStatusResponse) ProtoMessage() {}

func (x *ServeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsnet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeStatusResponse.ProtoReflect.Descriptor instead.
func (*ServeStatusResponse) Descriptor() ([]byte, []int) {
	return file_tsnet_proto_rawDescGZIP(), []int{11}
}

func (x *ServeStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ServeStatusResponse) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *ServeStatusResponse) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *ServeStatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

var File_tsnet_proto protoreflect.FileDescriptor

const file_tsnet_proto_rawDesc = "" +
	"\n" +
	"\vtsnet.proto\x12\btsnet.v1\"\xa2\x01\n" +
	"\fStartRequest\x12\x1f\n" +
	"\vcontrol_url\x18\x01 \x01(\tR\n" +
	"controlUrl\x12\x19\n" +
	"\bauth_key\x18\x02 \x01(\tR\aauthKey\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"socks_port\x18\x04 \x01(\rR\tsocksPort\x12\x1b\n" +
	"\tallow_net\x18\x05 \x03(\tR\ballowNet\"t\n" +
	"\rStartResponse\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.tsnet.v1.TsnetStateR\x05state\x12\x1d\n" +
	"\n" +
	"socks_port\x18\x02 \x01(\rR\tsocksPort\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"#\n" +
	"\vStopRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"T\n" +
	"\fStopResponse\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.tsnet.v1.TsnetStateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"\x98\x01\n" +
	"\x0eStatusResponse\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.tsnet.v1.TsnetStateR\x05state\x12\x1d\n" +
	"\n" +
	"socks_port\x18\x02 \x01(\rR\tsocksPort\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"P\n" +
	"\fServeRequest\x12\x1f\n" +
	"\vtarget_addr\x18\x01 \x01(\tR\n" +
	"targetAddr\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\rR\n" +
	"listenPort\"\x85\x01\n" +
	"\rServeResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\rR\n" +
	"listenPort\x12\x1f\n" +
	"\vlisten_addr\x18\x03 \x01(\tR\n" +
	"listenAddr\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"(\n" +
	"\x10ServeStopRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"G\n" +
	"\x11ServeStopResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12ServeStatusRequest\"\x90\x01\n" +
	"\x13ServeStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\rR\n" +
	"listenPort\x12\x1f\n" +
	"\vlisten_addr\x18\x03 \x01(\tR\n" +
	"listenAddr\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError*\xa7\x01\n" +
	"\n" +
	"TsnetState\x12\x1b\n" +
	"\x17TSNET_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TSNET_STATE_STOPPED\x10\x01\x12\x18\n" +
	"\x14TSNET_STATE_STARTING\x10\x02\x12\x17\n" +
	"\x13TSNET_STATE_RUNNING\x10\x03\x12\x18\n" +
	"\x14TSNET_STATE_STOPPING\x10\x04\x12\x16\n" +
	"\x12TSNET_STATE_FAILED\x10\x052\x8d\x03\n" +
	"\fTsnetService\x128\n" +
	"\x05Start\x12\x16.tsnet.v1.StartRequest\x1a\x17.tsnet.v1.StartResponse\x125\n" +
	"\x04Stop\x12\x15.tsnet.v1.StopRequest\x1a\x16.tsnet.v1.StopResponse\x12;\n" +
	"\x06Status\x12\x17.tsnet.v1.StatusRequest\x1a\x18.tsnet.v1.StatusResponse\x12=\n" +
	"\n" +
	"StartServe\x12\x16.tsnet.v1.ServeRequest\x1a\x17.tsnet.v1.ServeResponse\x12D\n" +
	"\tStopServe\x12\x1a.tsnet.v1.ServeStopRequest\x1a\x1b.tsnet.v1.ServeStopResponse\x12J\n" +
	"\vServeStatus\x12\x1c.tsnet.v1.ServeStatusRequest\x1a\x1d.tsnet.v1.ServeStatusResponseB Z\x1egithub.com/ato/ato-tsnetd;mainb\x06proto3"

var (
	file_tsnet_proto_rawDescOnce sync.Once
	file_tsnet_proto_rawDescData []byte
)

func file_tsnet_proto_rawDescGZIP() []byte {
	file_tsnet_proto_rawDescOnce.Do(func() {
		file_tsnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tsnet_proto_rawDesc), len(file_tsnet_proto_rawDesc)))
	})
	return file_tsnet_proto_rawDescData
}

var file_tsnet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tsnet_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tsnet_proto_goTypes = []any{
	(TsnetState)(0),             // 0: tsnet.v1.TsnetState
	(*StartRequest)(nil),        // 1: tsnet.v1.StartRequest
	(*StartResponse)(nil),       // 2: tsnet.v1.StartResponse
	(*StopRequest)(nil),         // 3: tsnet.v1.StopRequest
	(*StopResponse)(nil),        // 4: tsnet.v1.StopResponse
	(*StatusRequest)(nil),       // 5: tsnet.v1.StatusRequest
	(*StatusResponse)(nil),      // 6: tsnet.v1.StatusResponse
	(*ServeRequest)(nil),        // 7: tsnet.v1.ServeRequest
	(*ServeResponse)(nil),       // 8: tsnet.v1.ServeResponse
	(*ServeStopRequest)(nil),    // 9: tsnet.v1.ServeStopRequest
	(*ServeStopResponse)(nil),   // 10: tsnet.v1.ServeStopResponse
	(*ServeStatusRequest)(nil),  // 11: tsnet.v1.ServeStatusRequest
	(*ServeStatusResponse)(nil), // 12: tsnet.v1.ServeStatusResponse
}
var file_tsnet_proto_depIdxs = []int32{
	0,  // 0: tsnet.v1.StartResponse.state:type_name -> tsnet.v1.TsnetState
	0,  // 1: tsnet.v1.StopResponse.state:type_name -> tsnet.v1.TsnetState
	0,  // 2: tsnet.v1.StatusResponse.state:type_name -> tsnet.v1.TsnetState
	1,  // 3: tsnet.v1.TsnetService.Start:input_type -> tsnet.v1.StartRequest
	3,  // 4: tsnet.v1.TsnetService.Stop:input_type -> tsnet.v1.StopRequest
	5,  // 5: tsnet.v1.TsnetService.Status:input_type -> tsnet.v1.StatusRequest
	7,  // 6: tsnet.v1.TsnetService.StartServe:input_type -> tsnet.v1.ServeRequest
	9,  // 7: tsnet.v1.TsnetService.StopServe:input_type -> tsnet.v1.ServeStopRequest
	11, // 8: tsnet.v1.TsnetService.ServeStatus:input_type -> tsnet.v1.ServeStatusRequest
	2,  // 9: tsnet.v1.TsnetService.Start:output_type -> tsnet.v1.StartResponse
	4,  // 10: tsnet.v1.TsnetService.Stop:output_type -> tsnet.v1.StopResponse
	6,  // 11: tsnet.v1.TsnetService.Status:output_type -> tsnet.v1.StatusResponse
	8,  // 12: tsnet.v1.TsnetService.StartServe:output_type -> tsnet.v1.ServeResponse
	10, // 13: tsnet.v1.TsnetService.StopServe:output_type -> tsnet.v1.ServeStopResponse
	12, // 14: tsnet.v1.TsnetService.ServeStatus:output_type -> tsnet.v1.ServeStatusResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tsnet_proto_init() }
func file_tsnet_proto_init() {
	if File_tsnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tsnet_proto_rawDesc), len(file_tsnet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tsnet_proto_goTypes,
		DependencyIndexes: file_tsnet_proto_depIdxs,
		EnumInfos:         file_tsnet_proto_enumTypes,
		MessageInfos:      file_tsnet_proto_msgTypes,
	}.Build()
	File_tsnet_proto = out.File
	file_tsnet_proto_goTypes = nil
	file_tsnet_proto_depIdxs = nil
}
