// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: tsnet.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TsnetService_Start_FullMethodName       = "/tsnet.v1.TsnetService/Start"
	TsnetService_Stop_FullMethodName        = "/tsnet.v1.TsnetService/Stop"
	TsnetService_Status_FullMethodName      = "/tsnet.v1.TsnetService/Status"
	TsnetService_StartServe_FullMethodName  = "/tsnet.v1.TsnetService/StartServe"
	TsnetService_StopServe_FullMethodName   = "/tsnet.v1.TsnetService/StopServe"
	TsnetService_ServeStatus_FullMethodName = "/tsnet.v1.TsnetService/ServeStatus"
)

// TsnetServiceClient is the client API for TsnetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TsnetServiceClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	StartServe(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeResponse, error)
	StopServe(ctx context.Context, in *ServeStopRequest, opts ...grpc.CallOption) (*ServeStopResponse, error)
	ServeStatus(ctx context.Context, in *ServeStatusRequest, opts ...grpc.CallOption) (*ServeStatusResponse, error)
}

type tsnetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTsnetServiceClient(cc grpc.ClientConnInterface) TsnetServiceClient {
	return &tsnetServiceClient{cc}
}

func (c *tsnetServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, TsnetService_Start_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsnetServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, TsnetService_Stop_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsnetServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TsnetService_Status_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsnetServiceClient) StartServe(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeResponse, error) {
	out := new(ServeResponse)
	err := c.cc.Invoke(ctx, TsnetService_StartServe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsnetServiceClient) StopServe(ctx context.Context, in *ServeStopRequest, opts ...grpc.CallOption) (*ServeStopResponse, error) {
	out := new(ServeStopResponse)
	err := c.cc.Invoke(ctx, TsnetService_StopServe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsnetServiceClient) ServeStatus(ctx context.Context, in *ServeStatusRequest, opts ...grpc.CallOption) (*ServeStatusResponse, error) {
	out := new(ServeStatusResponse)
	err := c.cc.Invoke(ctx, TsnetService_ServeStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TsnetServiceServer is the server API for TsnetService service.
// All implementations must embed UnimplementedTsnetServiceServer
// for forward compatibility
type TsnetServiceServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	StartServe(context.Context, *ServeRequest) (*ServeResponse, error)
	StopServe(context.Context, *ServeStopRequest) (*ServeStopResponse, error)
	ServeStatus(context.Context, *ServeStatusRequest) (*ServeStatusResponse, error)
	mustEmbedUnimplementedTsnetServiceServer()
}

// UnimplementedTsnetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTsnetServiceServer struct {
}

func (UnimplementedTsnetServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedTsnetServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedTsnetServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedTsnetServiceServer) StartServe(context.Context, *ServeRequest) (*ServeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartServe not implemented")
}
func (UnimplementedTsnetServiceServer) StopServe(context.Context, *ServeStopRequest) (*ServeStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopServe not implemented")
}
func (UnimplementedTsnetServiceServer) ServeStatus(context.Context, *ServeStatusRequest) (*ServeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServeStatus not implemented")
}
func (UnimplementedTsnetServiceServer) mustEmbedUnimplementedTsnetServiceServer() {}

// UnsafeTsnetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TsnetServiceServer will
// result in compilation errors.
type UnsafeTsnetServiceServer interface {
	mustEmbedUnimplementedTsnetServiceServer()
}

func RegisterTsnetServiceServer(s grpc.ServiceRegistrar, srv TsnetServiceServer) {
	s.RegisterService(&TsnetService_ServiceDesc, srv)
}

func _TsnetService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsnetServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsnetService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsnetServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsnetService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsnetServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsnetService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsnetServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsnetService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsnetServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsnetService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsnetServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsnetService_StartServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsnetServiceServer).StartServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsnetService_StartServe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsnetServiceServer).StartServe(ctx, req.(*ServeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsnetService_StopServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServeStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsnetServiceServer).StopServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsnetService_StopServe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsnetServiceServer).StopServe(ctx, req.(*ServeStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsnetService_ServeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsnetServiceServer).ServeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsnetService_ServeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsnetServiceServer).ServeStatus(ctx, req.(*ServeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TsnetService_ServiceDesc is the grpc.ServiceDesc for TsnetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TsnetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tsnet.v1.TsnetService",
	HandlerType: (*TsnetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _TsnetService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _TsnetService_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _TsnetService_Status_Handler,
		},
		{
			MethodName: "StartServe",
			Handler:    _TsnetService_StartServe_Handler,
		},
		{
			MethodName: "StopServe",
			Handler:    _TsnetService_StopServe_Handler,
		},
		{
			MethodName: "ServeStatus",
			Handler:    _TsnetService_ServeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tsnet.proto",
}
