[package]
name = "ato-cli"
version = "0.7.9"
edition = "2024"
description = "Ato command line interface for addressable computations"
authors = ["ato-run"]
homepage = "https://ato.run"
license = "Apache-2.0 OR MPL-2.0"
repository = "https://github.com/ato-run/ato"
build = "build.rs"

[package.metadata.ato-architecture]
layer = "app"

[package.metadata.wix]
upgrade-guid = "91E1EDBC-3923-4EB3-8AD9-02239A1537BA"
path-guid = "6DBB2927-20CD-429F-BAD0-687E62082ED6"
license = false
eula = false

[[bin]]
name = "ato"
path = "src/main.rs"

[dependencies]
anyhow = "1"
ato-adapter-repository = { path = "../../extensions/adapters/repository", version = "0.1.0" }
ato-computation = { path = "../../lib/computation", version = "0.1.0" }
ato-ipc = { path = "../../lib/ipc", version = "0.1.0" }
ato-kernel = { path = "../../lib/kernel", version = "0.1.0" }
ato-objects = { path = "../../lib/objects", version = "0.1.0" }
ato-provider-nacelle = { path = "../../extensions/providers/nacelle", version = "0.7.9" }
ato-provider-snapshot = { path = "../../extensions/providers/snapshot", version = "0.1.0" }
ato-semantics-compose = { path = "../../extensions/semantics/compose", version = "0.1.0" }
ato-semantics-workspace = { path = "../../extensions/semantics/workspace", version = "0.1.0" }
blake3 = "1"
clap = { version = "4.5", features = ["derive", "env"] }
dirs = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
