pub const EXIT_USER_ERROR: i32 = 1;
pub const EXIT_SYSTEM_ERROR: i32 = 2;
pub const EXIT_NETWORK_ERROR: i32 = 3;
pub const EXIT_RUNTIME_ERROR: i32 = 5;

pub const ATO_ERR_AUTH_REQUIRED: &str = "ATO_ERR_AUTH_REQUIRED";
pub const ATO_ERR_INTEGRITY_FAILURE: &str = "ATO_ERR_INTEGRITY_FAILURE";
